export const copy = {
  meta: {
    title: "FACT · MVP 工作台（M0 + M1）",
    prototype: "交互原型 / Interactive prototype",
    synthetic: "演示数据 / Synthetic data",
    version: "v0.8 · 2026-09-27",
  },
  brand: {
    mark: "T",
    name: "Relativity 中文原型 / Chinese Prototype",
    shortName: "Relativity 原型 / Prototype",
  },
  workspace: {
    client: "Close AI Ltd.",
    matter: "高管马克欺诈项目调查 / Project Mark Fraud",
    name: "马克欺诈项目工作区 / MF Workspace",
    switchLabel: "切换工作区 / Switch workspace",
    allWorkspaces: "所有工作区 / All workspaces",
    role: "工作区管理员 / Workspace admin",
    user: "林然 / Ran Lin",
  },
  common: {
    priorityP0: "P0 核心 / Core",
    priorityP1: "P1 闭环 / Completion",
    featureIds: "功能 ID / Feature IDs",
    scope: "范围追溯 / Scope trace",
    search: "搜索 / Search",
    clear: "清除 / Clear",
    cancel: "取消 / Cancel",
    close: "关闭 / Close",
    confirm: "确认 / Confirm",
    save: "保存 / Save",
    saveNext: "保存并下一份 / Save & Next",
    edit: "编辑 / Edit",
    retry: "重试 / Retry",
    download: "下载 / Download",
    export: "导出 / Export",
    view: "查看 / View",
    continue: "继续 / Continue",
    back: "返回 / Back",
    next: "下一步 / Next",
    run: "运行 / Run",
    new: "新建 / New",
    create: "创建 / Create",
    refresh: "刷新 / Refresh",
    more: "更多 / More",
    selected: "已选择 / Selected",
    total: "总计 / Total",
    completed: "已完成 / Completed",
    inProgress: "进行中 / In progress",
    waiting: "等待中 / Waiting",
    failed: "失败 / Failed",
    partial: "部分完成 / Partial",
    ready: "就绪 / Ready",
    draft: "草稿 / Draft",
    active: "活动 / Active",
    all: "全部 / All",
    settings: "设置 / Settings",
    openMenu: "打开菜单 / Open menu",
    collapse: "收起 / Collapse",
    expand: "展开 / Expand",
    previous: "上一项 / Previous",
    nextItem: "下一项 / Next",
    firstPage: "第一页 / First page",
    previousPage: "上一页 / Previous page",
    nextPage: "下一页 / Next page",
    lastPage: "最后一页 / Last page",
    rowsPerPage: "每页 25 条 / 25 per page",
    paginationRange: "1–25",
    paginationTotal: "/ 127",
    demoOnly: "仅用于流程演示，不代表真实租户配置 / For workflow demonstration only; not a live tenant configuration",
    unavailable: "暂不可用 / Unavailable",
    open: "打开 / Open",
    details: "详情 / Details",
    notifications: "通知 / Notifications",
    help: "帮助 / Help",
    userOptions: "用户选项 / User options",
  },
  navigation: [
    { id: "workspaces", label: "客户、事项与工作区 / Clients, Matters & Workspaces", short: "工作区\nWorkspaces" },
    { id: "users", label: "用户与组管理 / User and Group Management", short: "用户与组\nUsers & Groups" },
    { id: "fields", label: "字段与布局 / Fields & Layouts", short: "字段与布局\nFields & Layouts" },
    { id: "home", label: "概览 / Overview", short: "概览\nOverview" },
    { id: "processing", label: "处理 / Processing", short: "处理\nProcessing" },
    { id: "documents", label: "文档 / Documents", short: "文档\nDocuments" },
    { id: "analytics", label: "搜索与分析 / Search & Analytics", short: "分析\nAnalytics" },
    { id: "review", label: "审阅 / Review", short: "审阅\nReview" },
    { id: "redaction", label: "成像与遮盖 / Imaging & Redact", short: "遮盖\nRedact" },
    { id: "production", label: "制作与导出 / Production & Export", short: "制作\nProduction" },
    { id: "tasks", label: "任务中心 / Task Center", short: "任务\nTasks" },
  ],
  fieldManagement: {
    title: "字段与布局 / Fields & Layouts",
    subtitle: "工作区设置 / Workspace Setup",
    ids: "Fields · Choices · Field Categories · Layouts",
    layouts: "布局 / Layouts",
    fields: "字段 / Fields", choices: "选项 / Choices", categories: "字段分类 / Field Categories",
    allFields: "全部字段 / All Fields", allCategories: "全部字段分类 / All Field Categories",
    newField: "新建字段 / New Field", newCategory: "新建字段分类 / New Field Category",
    fieldInformation: "字段信息 / Field Information", categoryDetails: "分类详情 / Category Details",
    objectType: "对象类型 / Object Type", document: "文档 / Document", fieldType: "字段类型 / Field Type",
    typeHint: "选择对象类型和字段类型以查看相关设置。 / Select an Object Type and Field Type to see relevant settings.",
    typeOptions: [
      { id: "currency", label: "货币 / Currency" }, { id: "date", label: "日期 / Date" },
      { id: "decimal", label: "小数 / Decimal" }, { id: "text", label: "定长文本 / Fixed-Length Text" },
      { id: "longText", label: "长文本 / Long Text" }, { id: "multiple", label: "多选 / Multiple Choice" },
      { id: "multipleObject", label: "多对象 / Multiple Object" }, { id: "single", label: "单选 / Single Choice" },
      { id: "singleObject", label: "单对象 / Single Object" }, { id: "boolean", label: "是／否 / Yes/No" },
    ],
    fieldSettings: "字段设置 / Field Settings", advancedSettings: "高级设置 / Advanced Settings",
    advancedUnavailable: "截图未展开此设置 / This setting is not shown in the reference screenshots",
    settings: [
      ["必填 / Required", "否 / No"],
      ["可用于字段树 / Available in Field Tree", "是 / Yes"],
      ["默认覆盖行为 / Default Overlay Behavior", "合并值 / Merge Values"],
    ],
    dashboard: "列表和仪表盘设置 / List and Dashboard Settings",
    dashboardSettings: [
      ["筛选类型 / Filter Type", "多选列表 / Multi-list"],
      ["启用排序／计数 / Enable Sort/Tally", "是 / Yes"],
      ["启用分组 / Enable Group By", "是 / Yes"],
      ["启用透视 / Enable Pivot", "是 / Yes"],
    ],
    addChoice: "添加选项 / Add Choice", addList: "批量添加选项 / Add List of Choices",
    addChild: "添加子选项 / Add Child Choice", choiceName: "选项名称 / Choice Name",
    choiceDetails: "选项详情 / Choice Details", parentChoice: "父选项 / Parent Choice",
    listHint: "每行输入一个选项 / Enter one choice per line",
    fillExamples: "填入截图中的选项 / Use choices from screenshots",
    exampleChoices: ["Fraud", "False Accounting", "Payments", "Procurement", "Payroll", "Trade", "Data Theft", "Intellectual Property"],
    reorder: "按名称排序 / Reorder A–Z", filterChoices: "筛选选项 / Filter choices",
    filterFields: "筛选字段 / Filter fields", filterCategories: "筛选字段分类 / Filter field categories",
    selectChoices: "选择全部选项 / Select all choices", selectFields: "选择全部字段 / Select all fields",
    autoSaved: "更改自动保存在当前会话 / Changes saved automatically in this session",
    deleteSelected: "删除所选 / Delete selected", deleteChoices: "删除选项 / Delete choices",
    deleteChoicesHint: "将删除所选选项及其全部子选项。 / Delete the selected choices and all their descendants.",
    order: "顺序 / Order", viewOrder: "查看顺序 / View Order", orderReference: "顺序参考 / Order Reference",
    orderHint: "数值越小越靠前；输入小于 10 的数值可排在默认分类之前。 / Lower values appear first; use a value below 10 to precede the default categories.",
    defaultOrder: 0,
    link: "关联 / Link", unlink: "取消关联 / Unlink", selectFieldsTitle: "选择字段 / Select Items - Fields",
    availableFields: "可用字段 / Available Fields", selectedFields: "已选字段 / Selected Fields",
    chooseField: "选择字段 / Select field", noChoiceField: "请先创建多选字段。 / Create a Multiple Choice field first.",
    fieldSaved: "字段已保存 / Field saved", categorySaved: "字段分类已保存 / Field category saved",
    choicesSaved: "选项已保存 / Choices saved", linked: "字段关联已保存 / Field links saved",
    unlinked: "字段已取消关联 / Fields unlinked", deleted: "记录已删除 / Record deleted",
    duplicateField: "同一对象下已存在同名字段。 / A field with this name already exists on this object.",
    duplicateCategory: "已存在同名字段分类。 / A field category with this name already exists.",
    duplicateChoice: "同一父选项下的名称不能重复。 / Choice names must be unique within the same parent.",
    choiceRequired: "请至少输入一个选项名称。 / Enter at least one choice name.",
    invalidOrder: "顺序必须是非负整数。 / Order must be a non-negative integer.",
    deleteTitle: "删除记录 / Delete record",
    deleteFieldHint: "将删除此字段及其选项，并移除分类中的关联。 / Delete this field and its choices, and remove its category links.",
    deleteCategoryHint: "将删除此分类；已关联的字段仍然保留。 / Delete this category; linked fields will be retained.",
    localOnly: "配置保留在当前浏览器会话中，刷新后恢复初始数据。 / Configuration is kept in this browser session; refreshing restores initial data.",
    actions: "操作 / Actions", separator: "：", branch: "└", empty: "—",
    columns: ["名称 / Name", "对象类型 / Object Type", "字段类型 / Field Type", "字段分类 / Field Categories"],
    categoryColumns: ["名称 / Name", "顺序 / Order", "字段 / Fields"],
    seedFields: [
      { id: "control-number", name: "Control Number", type: "text" },
      { id: "extracted-text", name: "Extracted Text", type: "longText" },
    ],
    seedCategories: [
      { id: "default", name: "Default Fields", order: 10, fieldIds: ["control-number", "extracted-text"] },
      { id: "email", name: "Email Fields", order: 20, fieldIds: [] },
      { id: "analytics", name: "Analytics Fields", order: 30, fieldIds: [] },
    ],
  },
  layoutManagement: {
    layouts: "布局 / Layouts",
    all: "全部布局 / All Layouts", new: "新建布局 / New Layout", information: "布局信息 / Layout Information",
    filter: "筛选布局 / Filter layouts", build: "构建布局 / Build Layout", editor: "编辑布局 / Edit Layout Information",
    copyPrevious: "启用复制上一份 / Enable Copy From Previous", overwrite: "覆盖保护 / Overwrite Protection",
    applications: "Relativity 应用 / Relativity Applications", disabled: "已禁用 / Disabled",
    defaultCategory: "默认分区 / Default Category", categoryName: "分区名称 / Category Name",
    addCategory: "添加分区 / Add Category", removeCategory: "删除分区 / Delete category",
    removeCategoryHint: "删除此分区及其布局项，字段本身保留。 / Remove this section and its layout items; the fields are retained.",
    moveUp: "上移分区 / Move category up", moveDown: "下移分区 / Move category down",
    options: "布局选项 / Layout Options", properties: "属性 / Properties", sectionProperties: "分区属性 / Section Properties", help: "上下文说明 / Contextual Help",
    helpEditor: "说明编辑器 / HTML Editor", editHelp: "编辑说明 / Edit contextual help",
    bold: "加粗 / Bold", italic: "斜体 / Italic", underline: "下划线 / Underline", bullets: "项目符号 / Bullets",
    helpExample: "填入截图说明 / Use screenshot instructions",
    exampleHelp: "Confirm document coding, redactions (if applicable), and production approval are complete. Identify issues as appropriate and assign to a production.",
    collapsible: "可折叠 / Collapsible", collapsed: "默认折叠 / Collapsed By Default",
    searchFields: "搜索要添加的字段 / Search for a field to add", emptyFields: "没有可添加的匹配字段 / No matching fields available",
    selectCategory: "先添加或选择一个分区，再添加字段。 / Add or select a category before adding a field.",
    dropField: "放置字段 / Drop Field", addField: "添加字段 / Add field", removeField: "移除字段 / Remove field",
    field: "字段 / Field", display: "显示方式 / Display Type", showName: "显示字段名 / Show Field Name",
    customLabel: "自定义标签 / Custom Label", readOnly: "只读 / Read-only", allowCopy: "允许复制上一份 / Allow Copy from Previous",
    copyDisabled: "请先在布局信息中启用复制上一份。 / Enable Copy From Previous in Layout Information first.",
    repeatColumns: "重复列数 / Repeat Columns", defaultRepeatColumns: 1, repeatOptions: [1, 2, 3, 4],
    displayOptions: { text: "文本框 / Text Box", dropdown: "下拉框 / Drop-down", checkbox: "复选框列表 / Check Box List" },
    column: "列 / Column", row: "行 / Row", left: "左列 / Left", right: "右列 / Right",
    saveClose: "保存并关闭 / Save and Close", saved: "布局已保存 / Layout saved", dirty: "尚有未保存的更改 / Unsaved changes",
    closeTitle: "关闭布局编辑器 / Close layout editor", discard: "放弃更改 / Discard changes", keepEditing: "继续编辑 / Keep editing",
    discardHint: "保存更改，或放弃上次保存之后的修改。 / Save changes or discard edits since the last save.",
    deleteTitle: "删除布局 / Delete layout", deleteHint: "删除此布局，字段和选项仍然保留。 / Delete this layout; fields and choices are retained.",
    duplicate: "已存在同名布局。 / A layout with this name already exists.",
    invalidCategory: "请为每个分区填写名称。 / Enter a name for each category.",
    fieldInUse: "此字段正在被布局使用，请先从布局中移除。 / This field is used in a layout. Remove it from the layout first.",
    loadFields: "载入截图示例字段 / Load screenshot fields", loadedFields: "示例字段已就绪，已有同名字段保持原值。 / Example fields ready; existing fields are preserved.",
    exampleFields: [
      { key: "custodian", name: "Custodian", type: "singleObject" },
      { key: "reviewComplete", name: "Review Complete - 2nd Level Review", type: "boolean" },
      { key: "responsiveness", name: "Responsiveness", type: "single" },
      { key: "privilege", name: "Privilege", type: "single" },
      { key: "confidentiality", name: "Confidentiality", type: "single" },
      { key: "issues", name: "Issues", type: "multiple" },
      { key: "privacy", name: "Privacy Redaction Completed", type: "boolean" },
      { key: "approvals", name: "Production Approvals", type: "multiple" },
      { key: "productions", name: "Productions", type: "multipleObject" },
    ],
    financial: "Financial",
    preview: "预览布局 / Preview layout", previewHint: "使用演示文档试填；关闭预览后不保留试填内容。 / Try with sample documents; entries are discarded when this preview closes.",
    previewDocument: "演示文档 / Sample document", previousCopy: "复制上一份 / Copy from previous", copied: "已复制允许复制的可编辑字段 / Eligible editable fields copied",
    previewDocuments: ["DEMO-0001", "DEMO-0002"], sampleCustodian: "林然 / Ran Lin",
    noChoices: "此字段尚未配置选项 / No choices configured for this field",
    noSections: "此布局尚未添加分区 / No categories in this layout", previewEmpty: "未填写 / Not entered",
    orderReferenceHint: "数值越小越靠前。 / Layouts with lower order values appear first.",
    columns: ["对象类型 / Object Type", "名称 / Name", "顺序 / Order", "启用复制上一份 / Enable Copy From Previous"],
    separator: " · ", numberingStart: 1, defaultOrder: 0,
  },
  workspaceManagement: {
    title: "客户、事项与工作区 / Clients, Matters & Workspaces",
    subtitle: "先确定客户和事项，再创建承载数据、权限与审阅流程的工作区 / Establish the client and matter before creating the workspace that contains data, permissions, and review workflows",
    ids: "Case Administration",
    tabs: [
      { id: "clients", label: "客户 / Clients" },
      { id: "matters", label: "事项 / Matters" },
      { id: "workspaces", label: "工作区 / Workspaces" },
    ],
    hierarchyTitle: "对象关系 / Object hierarchy",
    hierarchyClient: "客户 / Client",
    hierarchyMatter: "事项 / Matter",
    hierarchyWorkspace: "工作区 / Workspace",
    hierarchyDescription: "Client 管理委托方归属；Matter 记录具体案件或调查；Workspace 是导入、处理、搜索、审阅和交付实际发生的环境。 / Client identifies the organization, Matter records the case or investigation, and Workspace is where ingestion, processing, search, review, and production occur.",
    allClients: "全部客户 / All Clients",
    allMatters: "全部事项 / All Matters",
    allWorkspaces: "全部工作区 / All Workspaces",
    newClient: "新建客户 / New Client",
    newMatter: "新建事项 / New Matter",
    newWorkspace: "新建工作区 / New Workspace",
    listFeedback: "列表反馈 / List feedback",
    pinTitle: "固定常用工作区 / Pin Favorite Workspaces",
    pinDescription: "固定后，该工作区会显示在列表顶部。 / Pinned workspaces appear at the top of the list.",
    details: "记录详情 / Record details",
    selectRecord: "选择一条记录查看详情 / Select a record to view details",
    clientInformation: "客户信息 / Client Information",
    otherClientDetails: "其他客户信息 / Other Client Details",
    matterInformation: "事项信息 / Matter Information",
    workspaceInformation: "工作区信息 / Workspace Information",
    advancedSettings: "高级设置 / Advanced Settings",
    other: "其他 / Other",
    recordHistory: "记录历史 / Record History",
    name: "名称 / Name",
    number: "编号 / Number",
    clientNumber: "客户编号 / Client Number",
    matterNumber: "事项编号 / Matter Number",
    status: "状态 / Status",
    client: "客户 / Client",
    matter: "事项 / Matter",
    workspace: "工作区 / Workspace",
    templateWorkspace: "模板工作区 / Template Workspace",
    keywords: "关键词 / Keywords",
    notes: "备注 / Notes",
    clientDomainStatus: "客户域状态 / Client Domain Status",
    nonClientDomain: "非客户域 / Non-Client Domain",
    caseArtifactId: "Case Artifact ID",
    createdBy: "创建人 / Created by",
    createdOn: "创建时间 / Created on",
    lastModifiedBy: "最后修改人 / Last modified by",
    lastModifiedOn: "最后修改时间 / Last modified on",
    active: "活动 / Active",
    inactive: "停用 / Inactive",
    saveAndNew: "保存并新建 / Save & New",
    saveAndBack: "保存并返回 / Save & Back",
    editPermissions: "编辑权限 / Edit Permissions",
    viewAudit: "查看审计 / View Audit",
    delete: "删除 / Delete",
    pin: "固定工作区 / Pin workspace",
    unpin: "取消固定 / Unpin workspace",
    openWorkspace: "打开工作区 / Open workspace",
    select: "请选择 / Select",
    notProvided: "未填写 / Not provided",
    requiredHint: "请完成所有必填字段。 / Complete all required fields.",
    clientCreated: "客户已创建 / Client created",
    matterCreated: "事项已创建并关联客户 / Matter created and linked to client",
    workspaceCreated: "工作区已创建并继承事项与客户归属 / Workspace created with matter and client context",
    auditDemo: "审计记录已在详情中展示 / Audit history is shown in the details panel",
    permissionsDemo: "权限配置入口已打开（演示） / Permission editor opened (demo)",
    clientPlaceholder: "例如：ARK Industries / e.g. ARK Industries",
    clientNumberPlaceholder: "例如：12345 / e.g. 12345",
    matterPlaceholder: "例如：ARK Industries vs. Dknight Enterprises",
    matterNumberPlaceholder: "例如：MAT-2026-001",
    workspacePlaceholder: "例如：ARK Dknight Review",
    keywordsPlaceholder: "可选关键词 / Optional keywords",
    notesPlaceholder: "记录事项背景或管理备注 / Record matter context or administrative notes",
    columns: {
      clients: ["名称 / Name", "编号 / Number", "状态 / Status", "客户域 / Client Domain", "事项 / Matters"],
      matters: ["名称 / Name", "编号 / Number", "客户名称 / Client Name", "客户编号 / Client Number", "状态 / Status"],
      workspaces: ["固定 / Pin", "名称 / Name", "Case Artifact ID", "客户名称 / Client Name", "事项名称 / Matter Name", "状态 / Status"],
    },
    clients: [
      { id: "client-ark", name: "ARK Industries", number: "12345", status: "活动 / Active", domain: "非客户域 / Non-Client Domain" },
      { id: "client-close", name: "Close AI Ltd.", number: "CL-2026-008", status: "活动 / Active", domain: "客户域 / Client Domain" },
    ],
    matters: [
      { id: "matter-ark", name: "ARK Industries vs. Dknight Enterprises", number: "MAT-2026-001", clientId: "client-ark", clientName: "ARK Industries", clientNumber: "12345", status: "活动 / Active", keywords: "", notes: "" },
      { id: "matter-mark", name: "高管马克欺诈项目调查 / Project Mark Fraud", number: "MAT-2026-008", clientId: "client-close", clientName: "Close AI Ltd.", clientNumber: "CL-2026-008", status: "活动 / Active", keywords: "fraud", notes: "" },
    ],
    workspaces: [
      { id: "workspace-ark", name: "ARK Industries vs. Dknight Enterprises", matterId: "matter-ark", matterName: "ARK Industries vs. Dknight Enterprises", clientName: "ARK Industries", artifactId: "1387894", template: "RelativityOne Review Template (v4.0.0)", status: "活动 / Active", pinned: false },
      { id: "workspace-mark", name: "马克欺诈项目工作区 / MF Workspace", matterId: "matter-mark", matterName: "高管马克欺诈项目调查 / Project Mark Fraud", clientName: "Close AI Ltd.", artifactId: "1387942", template: "RelativityOne Investigations Template (v2.1.1)", status: "活动 / Active", pinned: true },
    ],
    templates: [
      "RelativityOne Review Template (v4.0.0)",
      "RelativityOne Review Template (v3.0.0)",
      "RelativityOne Investigations Template (v2.1.1)",
      "RelativityOne Hold and Collect Template (v2.0.2)",
      "RelativityOne ECA Template",
    ],
    history: {
      actor: "Moore, Scotti-Lynn",
      created: "2024-03-26 17:12 MDT",
      modified: "2024-03-26 17:12 MDT",
    },
  },
  permissionManagement: {
    title: "工作区安全 / Workspace Security", groups: "组 / Groups",
    features: "功能 / Features", objects: "对象安全 / Object Security", tabs: "标签可见性 / Tab Visibility", other: "其他设置 / Other Settings",
    selectedGroup: "所选组 / Selected Group", edit: "编辑权限 / Edit Permissions", copy: "复制 / Copy", preview: "预览 / Preview",
    loadExamples: "载入截图示例组 / Load example groups", examplesLoaded: "示例组已载入，可开始配置权限。 / Example groups loaded.",
    exampleHint: "可关联已有组，或载入教程中的示例组开始体验。 / Assign an existing group or load tutorial example groups.",
    search: "搜索权限 / Search permissions", details: "查看详情 / See Details", collapse: "收起详情 / Collapse details",
    role: "角色 / Role", reviewer: "审阅员 / Reviewer", powerUser: "高级用户 / Power User", administrator: "管理员 / Administrator",
    roleBoundary: "截图未展开 Administrator 的具体权限，本原型暂不提供该角色配置。 / Administrator permissions are not expanded in the screenshots and are unavailable in this prototype.",
    reviewActions: "审阅 — 操作 / Review — Actions", reviewApps: "审阅 — 应用 / Review — Applications",
    reviewCenter: "审阅中心 / Review Center", manageImage: "管理文档图像 / Manage Document Image", code: "修改文档元数据（编码）/ User Modify Document Metadata (Code)", sentiment: "查看情绪分析 / User View Sentiment Analysis",
    objectItems: "对象权限项 / Object Security Items", tabItems: "可见标签 / Tab Visibility Items",
    permissionName: "权限名称 / Permission Name", none: "无 / None", view: "查看 / View", editAction: "编辑 / Edit", deleteAction: "删除 / Delete", add: "添加 / Add", editSecurity: "编辑安全性 / Edit Sec",
    on: "开启 / On", off: "关闭 / Off", actions: "操作 / Actions",
    objectRows: [
      { id: "document", label: "文档 / Document" }, { id: "lists", label: "列表 / Lists" },
      { id: "search", label: "搜索 / Search" }, { id: "searchContainer", label: "搜索容器 / Search Container" },
      { id: "reviewCoding", label: "审阅中心编码 / Review Center Coding" }, { id: "reviewQueue", label: "审阅中心队列 / Review Center Queue" },
    ],
    documentActions: [{ id: "redactDocument", label: "遮盖文档 / Redact Document" }, { id: "addImage", label: "添加图像 / Add Image" }],
    tabRows: [
      { id: "reviewQueues", label: "审阅队列 / Review Queues" }, { id: "documents", label: "文档 / Documents" },
      { id: "reviewCenter", label: "审阅中心 / Review Center" }, { id: "lists", label: "列表 / Lists" },
      { id: "reviewManagement", label: "审阅管理 / Review Management" },
    ],
    settingSections: [
      { id: "browsers", label: "浏览器 / Browsers", items: [
        { id: "folders", label: "文件夹 / Folders" }, { id: "fieldTree", label: "字段树 / Field Tree" },
        { id: "savedSearches", label: "高级与已保存搜索 / Advanced & Saved Searches" }, { id: "documentPreview", label: "文档预览 / Document Preview" },
      ] },
      { id: "mass", label: "批量操作 / Mass Operations", items: [{ id: "exportFile", label: "导出至文件 / Export to File" }, { id: "saveList", label: "保存为列表 / Save as List" }] },
      { id: "admin", label: "管理操作 / Admin Operations", items: [{ id: "pivot", label: "使用透视表与图表 / Use Pivot/Chart" }, { id: "quickNav", label: "使用快速导航 / Use Quick Nav" }, { id: "exportDashboard", label: "导出仪表盘 / Export Dashboard" }] },
    ],
    reviewSave: "复核并保存 / Review and Save", revert: "撤回全部更改 / Revert All", summary: "复核权限变更 / Review Permissions Changes",
    summaryHint: "以下为本次修改的功能及细粒度权限，保存后对所选组生效。 / Review this session’s feature and granular changes before saving.",
    featureChanges: "功能变更 / Features changes", granularChanges: "细粒度权限变更 / Granular permissions changes",
    before: "修改前 / Before", after: "修改后 / After", noChanges: "没有待保存的变更。 / No pending changes.",
    saved: "组权限已保存。 / Group permissions saved.", discardTitle: "放弃未保存的权限更改？ / Discard unsaved permission changes?",
    discardMessage: "离开后将恢复上次保存的权限。 / Leaving restores the last saved permissions.", discard: "放弃更改 / Discard changes", keepEditing: "继续编辑 / Keep editing",
    copyTitle: "复制组权限 / Copy Group Permissions", copyFrom: "复制自 / Copy From", copyTo: "复制到 / Copy To", copyPermissions: "复制权限 / Copy Permissions",
    copyHint: "将用来源组的已保存权限替换目标组在当前工作区的权限。组成员不受影响。 / Replace the target’s permissions in this workspace with the source’s saved permissions. Membership is unchanged.",
    copied: "权限已复制。 / Permissions copied.", noSource: "请先关联另一个组作为权限来源。 / Assign another group to use as the source.",
    previewAs: "正在以此组成员身份预览 / Previewing as a member of", exitPreview: "退出预览 / Exit Preview",
    noTabs: "此组没有可预览的标签。 / No visible tabs for this group.", noObjectAccess: "此组无权查看此对象。 / This group cannot view this object.",
    noQueues: "没有可用队列 / No Queues Available", noAssignedQueues: "尚未分配任何队列。 / You have not been added to any queues.", noWorkspaceQueues: "工作区内没有审阅队列。 / No review queues in workspace.",
    library: "审阅库 / Review Library", queueTemplates: "队列模板 / Queue Templates", queueType: "队列类型 / Queue Type", savedSearch: "已保存搜索 / Saved Search", prioritized: "优先审阅 / Prioritized Review",
    libraryRows: ["1. 1st Level Review-Threaded", "2. 2nd Level Review-Privilege Term QC", "3. 2nd Level Review-Significant QC", "4. Prioritized Review", "5. Docs with Ranks Below Zero", "6. Images", "7. Spreadsheets", "8. Model/Reviewer QC", "9. New Blank Queue"], prioritizedRow: 3,
    documentColumns: ["控制编号 / Control Number", "文档族 / Family Group", "保管人 / Custodian", "记录类型 / Record Type"],
    workspaceInfo: "工作区信息 / Workspace Information", advanced: "高级设置 / Advanced Settings", workspaceAdminGroup: "工作区管理员组 / Workspace Admin Group", selectAdmin: "选择项目 — 工作区管理员组 / Select Item — Workspace Admin Group", set: "设置 / Set", advancedSaved: "工作区管理员组已保存。 / Workspace Admin Group saved.",
    seedGroupIdStart: 1389000,
    seedGroups: [
      { id: "example-administrator", name: "AF Administrator", assigned: true },
      { id: "example-attorneys", name: "AF Staff Attorneys", assigned: true },
      { id: "example-automated", name: "Automated Workflow Application", assigned: true },
      { id: "example-kcura", name: "kCura Admin Group", assigned: true },
      { id: "example-native", name: "NativeRedactServiceGroup", assigned: true },
      { id: "example-template-admin", name: "Review Template - Administrator", assigned: true },
      { id: "example-template-attorney", name: "Review Template - Attorney", assigned: true },
      { id: "example-template-level1", name: "Review Template - Level 1 Reviewer", assigned: true },
      { id: "example-template-level2", name: "Review Template - Level 2 Reviewer", assigned: true },
      { id: "example-template-manager", name: "Review Template - Review Manager", assigned: true },
      { id: "example-manager", name: "AF Review Manager", assigned: false },
      { id: "example-qc", name: "AF QC Reviewers", assigned: false },
    ],
    exampleDate: "2026-09-23", separator: " · ", valueSeparator: ", ",
  },
  userManagement: {
    title: "用户与组管理 / User and Group Management",
    subtitle: "创建用户，将用户加入组，再将组关联到工作区。用户通过所属组获得工作区访问权限。 / Create users, add users to groups, then associate groups with workspaces to grant access.",
    ids: "User and Group Management",
    users: "用户 / Users", groups: "组 / Groups",
    allUsers: "全部用户 / All Users", allGroups: "全部组 / All Groups",
    newUser: "新建用户 / New User", newGroup: "新建组 / New Group",
    userInformation: "用户信息 / User Information", otherUserDetails: "其他用户信息 / Other User Details",
    groupInformation: "组信息 / Group Information", otherGroupDetails: "其他组信息 / Other Group Details",
    firstName: "名 / First Name", lastName: "姓 / Last Name", email: "电子邮箱 / Email",
    fullName: "姓名 / Full Name", type: "类型 / Type", userType: "用户类型 / User Type",
    internal: "内部 / Internal", groupType: "组类型 / Group Type", systemGroup: "系统组 / System Group",
    access: "访问 / Access", relativityAccess: "Relativity 访问 / Relativity Access",
    disableOn: "停用日期（UTC）/ Disable On Date (UTC)", trustedIPs: "可信 IP / Trusted IPs",
    trustedIPsHint: "每行填写一个 IP 地址。 / Place each IP address on a separate line.",
    permissions: "权限 / Permissions", changeSettings: "更改设置 / Change Settings",
    changeViewer: "更改文档查看器 / Change Document Viewer", documentSkip: "文档跳过 / Document Skip",
    shortcuts: "键盘快捷键 / Keyboard Shortcuts", defaults: "默认设置 / Defaults",
    pageLength: "列表每页条数 / Item List Page Length", pageLengths: ["10", "25", "50", "100"],
    viewerPreference: "文档查看偏好 / Document Viewer Preference", viewer: "查看器 / Viewer",
    documentViewer: "文档查看器 / Document Viewer", defaultViewer: "默认 / Default",
    searchOwner: "已保存搜索所有者 / Saved Search Owner", public: "公开 / Public", user: "用户 / User",
    notifications: "用户组邮件通知 / User Group Email Notifications",
    notificationOptions: ["接收全部 / Receive All", "仅接收错误 / Receive Errors Only", "不接收 / Do Not Receive"],
    showFilters: "显示筛选器 / Show Filters", skipPreference: "文档跳过偏好 / Document Skip Preference", normal: "普通 / Normal",
    initialSettings: { pageLength: "25", viewerPreference: "查看器 / Viewer", searchOwner: "用户 / User", notifications: "接收全部 / Receive All" },
    enableUser: "启用用户 / Enable User",
    enableMessage: "启用 Relativity Access 后，此用户可访问 Relativity，并计入席位总数。是否继续？ / Setting Relativity Access to Yes allows access and counts this user toward the total seat count. Continue?",
    yes: "是 / Yes", no: "否 / No", enabled: "已启用 / Enabled", disabled: "已停用 / Disabled",
    requiredHint: "请填写所有必填字段，并选择客户。 / Complete all required fields and select a client.",
    invalidEmail: "请输入有效的电子邮箱。 / Enter a valid email address.",
    duplicateEmail: "该电子邮箱已存在。 / This email address already exists.",
    duplicateGroup: "该客户下已存在同名组。 / A group with this name already exists for the client.",
    invalidIPs: "请每行填写一个有效的 IPv4 或 IPv6 地址。 / Enter one valid IPv4 or IPv6 address per line.",
    invalidDate: "请选择有效的 UTC 停用日期和时间。 / Choose a valid UTC disable date and time.",
    userSaved: "用户已保存。 / User saved.", groupSaved: "组已保存。 / Group saved.",
    deleted: "记录已删除。 / Record deleted.", deleteTitle: "删除记录 / Delete record",
    deleteMessage: "删除用户会移除其组成员关系；删除组会移除其工作区关联。是否继续？ / Deleting a user removes group membership; deleting a group removes workspace associations. Continue?",
    noData: "暂无数据 / No data.", noUsers: "尚未创建用户，点击“新建用户”开始。 / Click New User to add your first user.",
    noGroups: "尚未创建组，点击“新建组”开始。 / Click New Group to create your first group.",
    searchUsers: "搜索姓名、邮箱或客户 / Search name, email or client", searchGroups: "搜索组名称或客户 / Search group name or client",
    total: "总计 / Total:", selected: "已选择 / Selected:", selectAll: "选择全部 / Select all",
    add: "添加 / Add", remove: "移除 / Remove", apply: "应用 / Apply", okay: "确定 / Okay",
    selectClient: "选择客户 / Select Client", clientSearch: "搜索客户 / Search clients",
    selectUsers: "选择项目 — 用户 / Select Items — Users", availableUsers: "可选用户 / Available Users", selectedUsers: "待加入的用户 / Selected Users",
    moveRight: "移至右侧 / Move to right", moveLeft: "移至左侧 / Move to left",
    moveAllRight: "全部移至右侧 / Move all to right", moveAllLeft: "全部移至左侧 / Move all to left",
    filter: "筛选 / Filter", addedTitle: "用户已加入组 / User(s) added to Group",
    addedMessage: "本地演示已完成成员更新。真实系统会提交后台任务，并根据通知设置发送完成邮件。 / Membership updated in this local demo. The live system submits a job and sends email according to notification settings.",
    removed: "已移除所选成员。 / Selected members removed.",
    manageWorkspacePermissions: "管理工作区权限 / Manage Workspace Permissions",
    selectedWorkspace: "所选工作区 / Selected Workspace", groupList: "组列表 / Group List",
    addRemoveGroups: "添加 / 移除组 / Add / Remove Groups", availableGroups: "可选组 / Available Groups",
    groupsInWorkspace: "工作区内的组 / Groups in Workspace", viewUsers: "查看用户 / View Users",
    permissionsSaved: "工作区的组关联已保存。 / Workspace group associations saved.",
    previewSecurity: "安全性预览 / Preview Security",
    securityBoundary: "用户通过所属组获得工作区权限，可编辑权限或预览组成员能看到的页面。 / Edit workspace group permissions or preview the pages available to group members.",
    localOnly: "本地交互演示；刷新页面后恢复初始数据，不会创建真实账号、计费或发送邮件。 / Local demo; reloading resets data. No live accounts, billing or emails.",
    accessHint: "工作区访问还取决于用户启用状态及停用日期。 / Workspace access also depends on the user's enabled status and disable date.",
    columns: {
      users: ["姓名 / Full Name", "客户 / Client", "电子邮箱 / E-mail Address", "客户名称 / Client Name", "用户类型 / User Type", "创建人 / Created By", "创建时间 / Created On"],
      groups: ["Artifact ID", "组名称 / Group Name", "客户 / Client"],
      members: ["姓名 / Full Name", "电子邮箱 / E-mail Address", "用户类型 / User Type"],
      workspaces: ["名称 / Name", "客户名称 / Client Name", "事项名称 / Matter Name", "状态 / Status"],
    },
    idStart: 1387968,
    nameSeparator: ", ",
    dateLocale: "zh-CN",
  },
  scope: {
    title: "P0 + P1 范围追溯 / P0 + P1 Scope Traceability",
    intro: "原型按 Relativity 原始功能结构呈现关键任务流。每个页面显示对应功能 ID；中文为对照翻译，不改变原始英文能力边界。 / The prototype follows the original Relativity capability structure. Each page shows source feature IDs; Chinese is a parallel translation and does not redefine the English capability boundary.",
    total: "127 项 / items",
    totalNumber: "127",
    p0: "57 项 P0 / P0 items",
    p1: "70 项 P1 / P1 items",
    groups: [
      { title: "数据输入与处理 / Data ingestion & processing", ids: "REL-063–083", count: "21 P0" },
      { title: "分析 / Analytics", ids: "REL-084–103", count: "20 P1" },
      { title: "文档、搜索与审阅 / Documents, search & review", ids: "REL-116–148", count: "33 P0" },
      { title: "成像、OCR 与 PDF / Imaging, OCR & PDF", ids: "REL-149–163", count: "15 P1" },
      { title: "遮盖 / Redact", ids: "REL-164–178", count: "15 P1" },
      { title: "制作 / Production", ids: "REL-179–192", count: "14 P1" },
      { title: "平台与审阅状态 / Platform & review status", ids: "REL-372–373, 379–380, 384, 390", count: "6 P1" },
      { title: "关系、传播与导入导出 / Relations, propagation & import/export", ids: "REL-386–387, 394", count: "3 P0" },
    ],
    boundaryTitle: "原型边界 / Prototype boundary",
    boundary: "已覆盖关键成功路径及处理异常、索引等待、审阅占用、遮盖泄漏检查和制作校验失败。未连接真实后端，也未验证真实租户中的按钮位置与权限组合。 / Covers the critical happy path plus processing exceptions, index waiting, review locks, redaction leak checks, and production validation failures. No live backend is connected, and exact controls or permission combinations have not been tenant-verified.",
  },
  home: {
    title: "工作区概览 / Workspace Overview",
    subtitle: "从数据进入到正式交付的当前状态 / Current state from ingestion through delivery",
    ids: "跨页面 / Cross-page",
    welcome: "下午好，林然 / Good afternoon, Ran",
    nextAction: "建议下一步 / Recommended next action",
    nextActionText: "复核 3 处待确认遮盖，然后运行制作前校验。 / Review 3 pending redactions, then run pre-production validation.",
    continueReview: "继续复核 / Continue QC",
    stagesTitle: "证据处理链 / Evidence workflow",
    stages: [
      { label: "导入与处理 / Ingest & Process", value: "12,480", detail: "11,946 已发布 / published", tone: "success", target: "processing" },
      { label: "搜索与分析 / Search & Analyze", value: "10,932", detail: "索引覆盖 / indexed", tone: "info", target: "analytics" },
      { label: "审阅 / Review", value: "4,280", detail: "2,914 已编码 / coded", tone: "warning", target: "review" },
      { label: "遮盖与质检 / Redact & QC", value: "86", detail: "3 待复核 / pending", tone: "danger", target: "redaction" },
      { label: "制作与导出 / Produce & Export", value: "1", detail: "草稿制作集 / draft set", tone: "neutral", target: "production" },
    ],
    metrics: [
      { label: "已发布文档 / Published documents", value: "11,946", delta: "+528 今日 / today" },
      { label: "待处理异常 / Open exceptions", value: "17", delta: "5 可重试 / retryable" },
      { label: "审阅完成率 / Review completion", value: "68.1%", delta: "+6.4% 本周 / this week" },
      { label: "制作阻断项 / Production blockers", value: "3", delta: "均来自遮盖质检 / all from redaction QC" },
    ],
    activityTitle: "最近活动 / Recent activity",
    activities: [
      { time: "14:42", actor: "周宁 / Ning Zhou", action: "提交了遮盖复核 / submitted redaction QC", object: "REL00010342" },
      { time: "14:18", actor: "系统 / System", action: "完成增量索引 / completed incremental index", object: "dtSearch - Morninglight" },
      { time: "13:56", actor: "林然 / Ran Lin", action: "保存了搜索 / saved search", object: "First Pass - Contract Terms" },
      { time: "12:30", actor: "王辰 / Chen Wang", action: "重试处理异常 / retried processing exceptions", object: "PROC-2026-0918-04" },
    ],
    attentionTitle: "需要关注 / Needs attention",
    attention: [
      { title: "加密附件等待密码 / Encrypted attachments need passwords", detail: "8 个文件 / files", target: "processing" },
      { title: "一份文档被其他审阅人占用 / One document is checked out", detail: "REL00010331", target: "review" },
      { title: "遮盖文本层检查未通过 / Redacted text-layer check failed", detail: "3 处标记 / markups", target: "redaction" },
    ],
  },
  processing: {
    title: "处理 / Processing",
    subtitle: "Processing Source → Inventory → Discovery → Publish",
    ids: "REL-063–083, REL-394",
    createSource: "新建数据源 / New data source",
    processingSets: "处理集 / Processing Sets",
    sources: "数据源 / Data Sources",
    exceptions: "异常 / Exceptions",
    reports: "报告 / Reports",
    sourceName: "数据源名称 / Data source name",
    sourceNameValue: "董事邮箱补充批次 / Director mailbox supplement",
    sourceType: "输入方式 / Input method",
    rawFiles: "原始文件 / Raw files",
    structured: "结构化导入 / Structured import",
    uploadArea: "拖放文件到此处，或选择文件 / Drop files here, or choose files",
    uploadHint: "演示支持 PST、MSG、EML、PDF、DOCX、XLSX 和 ZIP / Demo accepts PST, MSG, EML, PDF, DOCX, XLSX, and ZIP",
    chooseFiles: "选择文件 / Choose files",
    profile: "处理配置 / Processing profile",
    profileValue: "中国项目默认配置 / China matter default",
    dedupe: "去重范围 / Deduplication scope",
    dedupeValue: "工作区级 / Workspace level",
    inventoryFirst: "先运行 Inventory / Run Inventory first",
    modalIntro: "本向导演示数据源创建，不会上传真实文件。 / This wizard demonstrates data-source creation and does not upload real files.",
    startUpload: "创建并开始上传 / Create & start upload",
    summary: [
      { label: "接收文件 / Received", value: "12,480" },
      { label: "发现项目 / Discovered", value: "18,226" },
      { label: "已发布 / Published", value: "11,946" },
      { label: "异常 / Exceptions", value: "17" },
    ],
    columns: ["处理集 / Processing Set", "阶段 / Stage", "进度 / Progress", "文档 / Documents", "异常 / Exceptions", "提交人 / Submitted by", "更新时间 / Updated"],
    rows: [
      { id: "PROC-2026-0918-04", name: "董事邮箱补充批次 / Director mailbox supplement", stage: "发布完成 / Published", progress: 100, docs: "528", exceptions: "4", owner: "王辰 / Chen Wang", updated: "今天 14:12 / Today 14:12", tone: "success" },
      { id: "PROC-2026-0917-02", name: "财务共享盘 / Finance shared drive", stage: "异常处理中 / Resolving exceptions", progress: 86, docs: "7,914", exceptions: "13", owner: "王辰 / Chen Wang", updated: "今天 13:48 / Today 13:48", tone: "warning" },
      { id: "PROC-2026-0915-01", name: "初始邮件批次 / Initial email set", stage: "发布完成 / Published", progress: 100, docs: "3,504", exceptions: "0", owner: "林然 / Ran Lin", updated: "9月18日 / Sep 18", tone: "success" },
    ],
    selectedTitle: "财务共享盘 / Finance shared drive",
    selectedStatus: "部分完成 / Partial completion",
    stages: [
      { order: "1", label: "上传 / Upload", status: "完成 / Complete", value: "4.8 GB" },
      { order: "2", label: "盘点 / Inventory", status: "完成 / Complete", value: "8,104 文件 / files" },
      { order: "3", label: "发现 / Discovery", status: "完成并有异常 / Complete with exceptions", value: "13 异常 / exceptions" },
      { order: "4", label: "发布 / Publish", status: "部分完成 / Partial", value: "7,914 文档 / documents" },
    ],
    exceptionTitle: "待处理异常 / Open exceptions",
    exceptionColumns: ["类型 / Type", "数量 / Count", "影响 / Impact", "建议操作 / Suggested action"],
    exceptionRows: [
      { type: "加密文件 / Encrypted files", count: "8", impact: "尚未发现内容 / Content not discovered", action: "添加密码并重试 / Add passwords & retry", tone: "warning" },
      { type: "文件损坏 / Corrupt files", count: "3", impact: "保留原件，无法预览 / Native retained, no preview", action: "下载并替换 / Download & replace", tone: "danger" },
      { type: "格式不支持 / Unsupported format", count: "2", impact: "未进入发布 / Not published", action: "查看文件清单 / View file list", tone: "neutral" },
    ],
    retrySuccess: "已将 8 个加密文件加入重试队列 / 8 encrypted files were queued for retry",
    createdSuccess: "已创建演示数据源并开始上传 / Demo data source created and upload started",
  },
  documents: {
    title: "文档 / Documents",
    subtitle: "筛选、搜索、保存结果并进入审阅 / Filter, search, save results, and open review",
    ids: "REL-116, REL-135–148, REL-386–387",
    allDocuments: "全部文档 / All Documents",
    savedSearches: "保存的搜索 / Saved Searches",
    folders: "文件夹 / Folders",
    folderItems: ["全部文档 / All Documents", "需一审 / First Pass", "合同与附件 / Contracts & Attachments", "遮盖候选 / Redaction Candidates", "待制作 / Production Candidates"],
    conditions: "搜索条件 / Search Conditions",
    conditionNumber: "1",
    addCondition: "添加条件 / Add Condition",
    runSearch: "运行搜索 / Run Search",
    autoRun: "自动运行 / Auto Run",
    conditionField: "字段 / Field",
    conditionFieldValue: "全文 / Extracted Text",
    conditionOperator: "运算符 / Operator",
    conditionOperatorValue: "包含 / Contains",
    conditionValue: "关键词或短语 / Keyword or phrase",
    searchValue: "termination agreement",
    indexCoverage: "索引覆盖 10,932 / 11,946 文档 / Indexed 10,932 of 11,946 documents",
    saveSearch: "保存搜索 / Save Search",
    savedSearchName: "搜索名称 / Search name",
    savedSearchNameValue: "First Pass - Termination Agreements",
    saveSearchSuccess: "搜索已保存 / Search saved",
    bulkEdit: "批量编辑 / Mass Edit",
    includeFamily: "包括家族 / Include Family",
    directHit: "直接命中 / Direct hit",
    familyHit: "家族扩展 / Family expansion",
    resultCount: "找到 7 个结果，其中 2 个来自家族扩展 / 7 results, including 2 from family expansion",
    columns: ["", "控制编号 / Control Number", "文件名 / File name", "记录类型 / Record Type", "响应性 / Responsiveness", "保密性 / Confidentiality", "关系 / Relation"],
    docs: [
      { id: "REL00010328", file: "Termination_Agreement_Draft.docx", type: "Microsoft Word", responsive: "响应 / Responsive", confidential: "保密 / Confidential", relation: "父件 / Parent", direct: true, locked: false },
      { id: "REL00010329", file: "Appendix_A_Pricing.xlsx", type: "Microsoft Excel", responsive: "响应 / Responsive", confidential: "保密 / Confidential", relation: "附件 / Attachment", direct: false, locked: false },
      { id: "REL00010330", file: "FW_Termination_timeline.msg", type: "Email", responsive: "待审阅 / Not Reviewed", confidential: "未设置 / Not Set", relation: "邮件链 / Email Thread", direct: true, locked: false },
      { id: "REL00010331", file: "Board_minutes_2025-03.pdf", type: "PDF", responsive: "待审阅 / Not Reviewed", confidential: "未设置 / Not Set", relation: "独立 / Standalone", direct: true, locked: true },
      { id: "REL00010332", file: "Termination_Agreement_Final.pdf", type: "PDF", responsive: "响应 / Responsive", confidential: "保密 / Confidential", relation: "近重复 / Near Duplicate", direct: true, locked: false },
      { id: "REL00010333", file: "Legal_comments.msg", type: "Email", responsive: "不响应 / Not Responsive", confidential: "特权 / Privileged", relation: "父件 / Parent", direct: true, locked: false },
      { id: "REL00010334", file: "Counsel_Memo.pdf", type: "PDF", responsive: "不响应 / Not Responsive", confidential: "特权 / Privileged", relation: "附件 / Attachment", direct: false, locked: false },
    ],
    lockedMessage: "该文档正由周宁审阅，请稍后重试 / This document is checked out by Ning Zhou; try again later",
    openReview: "在 Viewer 中打开 / Open in Viewer",
  },
  analytics: {
    title: "搜索与分析 / Search & Analytics",
    subtitle: "索引、邮件链、近重复与语言识别 / Indexes, email threads, near duplicates, and language identification",
    ids: "REL-084–101, REL-135–143, REL-148, REL-372–373",
    indexes: "搜索索引 / Search Indexes",
    structured: "结构化分析 / Structured Analytics",
    communication: "通信分析 / Communication Analysis",
    indexName: "dtSearch - Morninglight",
    indexStatus: "活动 / Active",
    indexCoverage: "10,932 / 11,946 文档 / documents",
    indexUpdated: "最后增量构建：今天 14:18 / Last incremental build: Today 14:18",
    incremental: "运行增量构建 / Run incremental build",
    rebuild: "完整重建 / Full rebuild",
    running: "正在构建索引 / Building index",
    runningDetail: "用户仍可搜索已索引的 10,932 份文档。 / Users can continue searching the 10,932 indexed documents.",
    runningProgress: 64,
    runSuccess: "增量索引任务已进入队列 / Incremental index job queued",
    analysisSets: "分析集 / Analysis Sets",
    newAnalysis: "新建分析集 / New analysis set",
    columns: ["分析集 / Analysis Set", "类型 / Type", "范围 / Scope", "状态 / Status", "结果 / Results", "更新时间 / Updated"],
    rows: [
      { name: "邮件主题与重复 / Email threads & duplicates", type: "邮件链 + 近重复 / Email Threading + TND", scope: "10,432", status: "完成 / Complete", result: "2,184 邮件链 / threads", updated: "今天 11:06 / Today 11:06", tone: "success" },
      { name: "语言识别 / Language identification", type: "语言 / Language", scope: "11,946", status: "完成 / Complete", result: "8 种语言 / languages", updated: "9月20日 / Sep 20", tone: "success" },
      { name: "合同概念聚类 / Contract concept clusters", type: "聚类 / Clustering", scope: "4,281", status: "部分完成 / Partial", result: "38 聚类 / clusters", updated: "9月20日 / Sep 20", tone: "warning" },
    ],
    threadTitle: "邮件链概览 / Email Thread Overview",
    threadStats: [
      { label: "邮件链 / Threads", value: "2,184" },
      { label: "可包含消息 / Inclusive emails", value: "3,912" },
      { label: "近重复组 / Near-duplicate groups", value: "604" },
      { label: "识别人物 / Normalized people", value: "328" },
    ],
    languageTitle: "语言分布 / Language Distribution",
    languages: [
      { label: "英语 / English", value: 62, count: "7,407" },
      { label: "简体中文 / Simplified Chinese", value: 28, count: "3,345" },
      { label: "繁体中文 / Traditional Chinese", value: 6, count: "717" },
      { label: "其他 / Other", value: 4, count: "477" },
    ],
    boundary: "Family、Email Thread 与 Near Duplicate 是不同关系，结果分别呈现。 / Family, Email Thread, and Near Duplicate are distinct relationships and are shown separately.",
  },
  review: {
    title: "审阅 / Review",
    subtitle: "Viewer、文档内搜索、编码与 Save & Next",
    ids: "REL-117–134, REL-144–145, REL-379–380, REL-386–387",
    queue: "一审优先队列 / First Pass Priority Queue",
    queueStatus: "活动 / Active",
    queueProgress: "2,914 / 4,280 已完成 / completed",
    returnQueue: "返回队列 / Return to queue",
    documentList: "文档列表 / Document list",
    viewerTabs: ["原生 / Native", "图像 / Image", "提取文本 / Extracted Text", "PDF / PDF"],
    findDocument: "文档内查找 / Find in document",
    findValue: "termination",
    hits: "3 个命中 / 3 hits",
    related: "相关项 / Related Items",
    family: "家族 / Family",
    emailThread: "邮件链 / Email Thread",
    nearDuplicate: "近重复 / Near Duplicate",
    history: "历史 / History",
    documentTitle: "Termination Agreement - Draft",
    documentMeta: "REL00010328 · Microsoft Word · 8 页 / pages",
    pageCount: "第 1 页，共 8 页 / Page 1 of 8",
    paperTitle: "TERMINATION AGREEMENT",
    paperSubtitle: "终止协议 / Termination Agreement",
    paperIntro: "This Termination Agreement is entered into as of March 14, 2025, by and between Northstar Holdings Ltd. and Morninglight Technology Co., Ltd.",
    paperSection: "1. Termination / 终止",
    paperBody: "The parties agree to terminate the Services Agreement. All confidential materials must be returned within thirty (30) days. The final payment schedule is attached as Appendix A.",
    paperConfidential: "CONFIDENTIAL - ATTORNEYS' EYES ONLY / 保密 - 仅限律师查看",
    coding: "编码面板 / Coding Panel",
    responsiveness: "响应性 / Responsiveness",
    responsivenessOptions: ["响应 / Responsive", "不响应 / Not Responsive", "需要进一步审阅 / Needs Further Review"],
    confidentiality: "保密性 / Confidentiality",
    confidentialityOptions: ["非保密 / Not Confidential", "保密 / Confidential", "特权 / Privileged"],
    issueTags: "问题标签 / Issue Tags",
    issueOptions: ["合同终止 / Contract Termination", "定价 / Pricing", "法律意见 / Legal Advice", "人员决策 / Personnel Decision"],
    notes: "审阅备注 / Review notes",
    notesPlaceholder: "输入仅供团队查看的备注 / Enter a team-only note",
    required: "必填 / Required",
    saved: "编码已保存，已进入下一份文档 / Coding saved; moved to next document",
    validation: "请完成响应性与保密性字段 / Complete Responsiveness and Confidentiality",
    copyPrevious: "复制上一份 / Copy previous",
    zoomIn: "放大 / Zoom in",
    zoomOut: "缩小 / Zoom out",
    rotate: "旋转 / Rotate",
    fullScreen: "全屏 / Full screen",
    documentItems: [
      { id: "REL00010328", label: "Termination Agreement", state: "当前 / Current", locked: false },
      { id: "REL00010330", label: "FW: Termination timeline", state: "未审阅 / Not reviewed", locked: false },
      { id: "REL00010331", label: "Board minutes", state: "周宁占用 / Locked by Ning", locked: true },
      { id: "REL00010332", label: "Termination Final", state: "未审阅 / Not reviewed", locked: false },
    ],
  },
  redaction: {
    title: "成像与遮盖 / Imaging & Redact",
    subtitle: "OCR、标记集、手工遮盖与多表示泄漏检查 / OCR, markup sets, manual redactions, and cross-representation leak checks",
    ids: "REL-149–178, REL-390",
    queue: "遮盖复核队列 / Redaction QC Queue",
    documentMeta: "REL00010342 · Employee_Settlement.pdf · 4 页 / pages",
    markupSet: "标记集 / Markup Set",
    markupSetValue: "敏感个人信息 / Personal Sensitive Data",
    reason: "遮盖原因 / Redaction Reason",
    reasonValue: "个人身份信息 / Personally Identifiable Information",
    tools: "遮盖工具 / Redaction Tools",
    rectangle: "矩形遮盖 / Rectangle redaction",
    fullPage: "整页遮盖 / Full-page redaction",
    text: "文本遮盖 / Text redaction",
    inverse: "反向遮盖 / Inverse redaction",
    applyDemo: "添加示例遮盖 / Add sample redaction",
    removeDemo: "移除示例遮盖 / Remove sample redaction",
    pageCount: "第 2 页，共 4 页 / Page 2 of 4",
    paperTitle: "EMPLOYEE SETTLEMENT SUMMARY",
    paperSubtitle: "员工和解摘要 / Employee Settlement Summary",
    employee: "Employee / 员工: Mei Zhang",
    address: "Address / 地址: 88 Huaxia Road, Shanghai",
    identity: "National ID / 身份证号: 310101199001012345",
    bank: "Bank account / 银行账户: 6222 0000 1234 5678",
    body: "The parties agree that the settlement amount and related terms remain confidential. Payment will be made within ten business days.",
    qc: "质检检查 / Quality Checks",
    qcItems: [
      { id: "image", label: "图像层已遮盖 / Image layer redacted", state: "通过 / Pass" },
      { id: "ocr", label: "OCR 文本层无残留 / OCR text layer clean", state: "失败 / Fail" },
      { id: "native", label: "Native 输出已排除 / Native output excluded", state: "通过 / Pass" },
      { id: "metadata", label: "元数据无敏感值 / Metadata contains no sensitive values", state: "待确认 / Pending" },
    ],
    runLeakCheck: "运行泄漏检查 / Run leak check",
    leakCheckRunning: "正在检查图像、OCR 文本、Native 与元数据 / Checking image, OCR text, native, and metadata",
    leakCheckSuccess: "泄漏检查通过，可以提交复核 / Leak check passed; ready for QC submission",
    submitQc: "提交复核 / Submit for QC",
    approve: "接受 / Accept",
    reject: "拒绝 / Reject",
    blocked: "OCR 文本层仍包含被遮盖内容，不能提交 / Redacted content remains in the OCR text layer; submission is blocked",
    submitted: "遮盖已提交复核 / Redactions submitted for QC",
    draftStatus: "草稿 / Draft",
    pendingStatus: "待复核 / Pending QC",
  },
  production: {
    title: "制作与导出 / Production & Export",
    subtitle: "固定范围、编号、表示版本、校验与交付清单 / Fixed scope, numbering, representations, validation, and delivery manifest",
    ids: "REL-179–192, REL-394",
    productionSet: "制作集 / Production Set",
    productionName: "晨光项目第一次制作 / Morninglight First Production",
    statusDraft: "草稿 / Draft",
    steps: ["1 范围 / Scope", "2 编号 / Branding", "3 输出 / Output", "4 校验 / Validate", "5 运行 / Run"],
    source: "文档来源 / Document source",
    sourceValue: "保存的搜索：Production Candidates / Saved Search: Production Candidates",
    fixedCount: "固定范围 1,248 份文档 / Fixed scope: 1,248 documents",
    numbering: "编号 / Bates numbering",
    prefix: "前缀 / Prefix",
    prefixValue: "MLP",
    startNumber: "起始编号 / Start number",
    startNumberValue: "000001",
    padding: "位数 / Digits",
    paddingValue: "6",
    output: "输出表示 / Output representations",
    outputOptions: [
      { id: "image", label: "单页 TIFF 图像 / Single-page TIFF images", checked: true },
      { id: "text", label: "提取文本 / Extracted text", checked: true },
      { id: "native", label: "符合条件的 Native / Eligible natives", checked: false },
      { id: "pdf", label: "合并 PDF / Combined PDF", checked: false },
      { id: "load", label: "DAT + Opticon load files / DAT + Opticon load files", checked: true },
    ],
    redactionSet: "使用的遮盖标记集 / Redaction markup set",
    redactionSetValue: "敏感个人信息 - 已接受 / Personal Sensitive Data - Accepted",
    placeholder: "占位页文字 / Placeholder text",
    placeholderValue: "DOCUMENT WITHHELD - PRIVILEGED / 文档因特权不予提供",
    runValidation: "运行制作前校验 / Run pre-production validation",
    validationTitle: "校验结果 / Validation Results",
    validationSummary: "1,248 份文档中有 3 项阻断问题 / 3 blocking issues across 1,248 documents",
    validationRows: [
      { check: "遮盖复核 / Redaction QC", result: "3 份未通过 / 3 failed", severity: "阻断 / Blocking", tone: "danger" },
      { check: "编号连续性 / Bates continuity", result: "通过 / Passed", severity: "正常 / Clear", tone: "success" },
      { check: "文件表示 / File representations", result: "通过 / Passed", severity: "正常 / Clear", tone: "success" },
      { check: "必填字段 / Required fields", result: "2 个警告 / 2 warnings", severity: "可继续 / Can proceed", tone: "warning" },
    ],
    resolveRedaction: "去处理遮盖问题 / Resolve redaction issues",
    rerunValidation: "重新校验 / Re-run validation",
    validationSuccess: "制作前校验已通过 / Pre-production validation passed",
    runProduction: "运行制作 / Run production",
    blocked: "存在阻断问题，不能运行制作 / Production cannot run while blocking issues remain",
    running: "制作运行中 / Production running",
    runningDetail: "正在生成图像、文本与 load files / Generating images, text, and load files",
    completed: "制作完成 / Production complete",
    completedDetail: "1,248 份文档 · 3.6 GB · MLP000001–MLP003842 / 1,248 documents · 3.6 GB · MLP000001–MLP003842",
    manifest: "下载交付清单 / Download delivery manifest",
    package: "下载制作包 / Download production package",
  },
  tasks: {
    title: "任务中心 / Task Center",
    subtitle: "跨工作区查看后台任务、错误和重试 / Monitor background jobs, errors, and retries across the workspace",
    ids: "REL-077–080, REL-149–163, REL-179–192, REL-372–373",
    filters: ["全部 / All", "运行中 / Running", "已完成 / Completed", "需要处理 / Needs action"],
    columns: ["任务 / Task", "对象 / Object", "状态 / Status", "进度 / Progress", "发起人 / Started by", "开始时间 / Started", "耗时 / Duration"],
    rows: [
      { task: "增量索引 / Incremental index", object: "dtSearch - Morninglight", status: "运行中 / Running", progress: 64, owner: "林然 / Ran Lin", started: "15:04", duration: "6 分钟 / min", tone: "info" },
      { task: "处理异常重试 / Processing exception retry", object: "PROC-2026-0917-02", status: "排队 / Queued", progress: 0, owner: "王辰 / Chen Wang", started: "15:08", duration: "—", tone: "neutral" },
      { task: "OCR 集 / OCR Set", object: "扫描合同补充 / Scanned contract supplement", status: "已完成 / Completed", progress: 100, owner: "系统 / System", started: "14:20", duration: "28 分钟 / min", tone: "success" },
      { task: "分析集 / Analytics Set", object: "合同概念聚类 / Contract concept clusters", status: "部分完成 / Partial", progress: 82, owner: "林然 / Ran Lin", started: "昨天 / Yesterday", duration: "47 分钟 / min", tone: "warning" },
      { task: "制作校验 / Production validation", object: "Morninglight First Production", status: "需要处理 / Needs action", progress: 100, owner: "林然 / Ran Lin", started: "14:58", duration: "2 分钟 / min", tone: "danger" },
    ],
    detailTitle: "任务详情 / Task Details",
    logTitle: "运行记录 / Run log",
    log: [
      "15:04:12 · 已创建增量构建 / Incremental build created",
      "15:04:18 · 已锁定索引配置 / Index configuration locked",
      "15:05:02 · 已处理 6,842 / 10,932 文档 / documents processed",
      "15:10:26 · 当前吞吐 720 文档/分钟 / Current throughput: 720 docs/min",
    ],
  },
  overlays: {
    notificationTitle: "通知 / Notifications",
    notifications: [
      { title: "遮盖泄漏检查失败 / Redaction leak check failed", detail: "REL00010342 · 3 分钟前 / 3 min ago", tone: "danger" },
      { title: "索引任务已开始 / Index job started", detail: "dtSearch - Morninglight · 8 分钟前 / 8 min ago", tone: "info" },
      { title: "处理异常已重试 / Processing exceptions retried", detail: "8 个文件 / files · 12 分钟前 / 12 min ago", tone: "success" },
    ],
    userTitle: "用户选项 / User Options",
    userItems: ["个人资料 / Profile", "界面偏好 / Preferences", "键盘快捷键 / Keyboard shortcuts", "退出 / Sign out"],
    helpTitle: "原型说明 / Prototype Help",
    helpText: "使用左侧导航体验完整流程。带 P0/P1 标签和 REL 编号的区域可追溯到当前优先级功能清单。 / Use the left navigation to explore the end-to-end flow. P0/P1 badges and REL IDs trace back to the current prioritized feature list.",
    noBackend: "这是可交互的前端原型，操作只改变当前浏览器中的演示状态。 / This is an interactive front-end prototype; actions only change demo state in this browser session.",
  },
  toasts: {
    generic: "操作已完成 / Action completed",
    copied: "已复制 / Copied",
    download: "演示文件已准备 / Demo file is ready",
  },
} as const;

export type PageId = (typeof copy.navigation)[number]["id"];


export const mvpCopy = {
  brand: "FACT", edition: "MVP · M0 + M1", title: "证据审阅工作台",
  prototype: "交互原型 · 数据仅保存在当前浏览器，未接入生产服务",
  header: { search: "搜索文档", scope: "本版范围", notifications: "通知", help: "帮助", user: "林然", menu: "打开菜单", synthetic: "演示数据", version: "v0.8 · 2026-09-27", demoOnly: "仅用于范围和流程讨论" },
  scope: "本版范围", scopeTitle: "M0 / M1 功能范围", scopeHint: "40 项 M0 + 18 项 M1。M2 与单列“条件必要”功能不在本版入口中；范围用于原型讨论，不代表后端已交付。",
  pages: [
    { id: "settings", name: "项目与配置", desc: "维护项目资料、成员、审阅表单和内部处理规则。" },
    { id: "processing", name: "导入与处理", desc: "核对材料、处理例外，再发布到文档库。" },
    { id: "documents", name: "文档与搜索", desc: "搜索、筛选和保存查询，按实际结果进入审阅。" },
    { id: "review", name: "文档审阅", desc: "阅读正文、记录判断，并保留修改历史。" },
    { id: "analytics", name: "索引与分析", desc: "查看索引覆盖，以及邮件链、近似文档和语言分析的示例结果。" },
    { id: "production", name: "交付与下载", desc: "冻结本次交付范围，检查后生成可下载的文本及元数据包。" },
    { id: "tasks", name: "任务与记录", desc: "查看每次操作的范围、结果和异常。" },
  ],
  settingsTabs: ["项目资料", "成员与角色", "字段与选项", "审阅表单", "处理规则", "备份与恢复"],
  roles: { admin: "管理员", reviewer: "审阅员", reader: "只读成员" },
  states: { ready: "可审阅", failed: "处理失败", staged: "待发布" },
  answers: { pending: "未审阅", relevant: "相关", irrelevant: "不相关", yes: "保密", no: "非保密" },
  tasks: { import: "导入", publish: "发布", index: "索引更新", analysis: "示例分析", export: "交付制作", retry: "重试" },
  all: "全部", none: "暂无记录", choose: "请选择", save: "保存", cancel: "取消", close: "关闭", edit: "编辑", create: "新建", name: "名称", status: "状态", action: "操作", source: "来源", date: "日期", type: "类型", document: "文档", id: "文档编号", file: "名称 / 主题", total: "文档总数", reviewed: "已审阅", indexed: "可搜索", failures: "处理失败", recent: "最近操作", time: "操作时间", actor: "操作人", detail: "详情", results: "结果", count: "数量", empty: "当前范围没有文档，请调整条件或先导入材料。", required: "请填写所有必填项。", duplicate: "名称或邮箱已存在，请使用不同值。", saved: "已保存到本浏览器。", storageError: "浏览器存储失败，本次操作没有保存。请先下载备份或减小导入量。", storageLoadError: "本地记录无法读取。为避免覆盖，已暂停写入；请先导出原记录或处理浏览器存储后刷新。", readonly: "当前角色不可执行此操作。", previewRole: "角色视角预览", roleHint: "仅模拟界面权限，不等同于真实账号登录或后端鉴权。", currentProject: "当前工作区", next: "下一页", prev: "上一页", page: "页", selected: "已选", clear: "清除", reset: "重置条件", open: "打开", yes: "是", no: "否", enabled: "启用", disabled: "停用", done: "完成", error: "失败", snapshot: "冻结范围", download: "下载", plus: "+", unknown: "未知", dash: "—",
  import: { fixture: "导入示例邮件包", local: "导入文本文件", inventory: "导入前盘点", submit: "开始导入", hint: "示例包用于演示邮件、附件、重复件和失败件。真实文件仅支持 UTF-8 .txt（每份不超过 2 MB）；Office、PST、OCR 等解析仍需后台接入。", preview: "盘点结果", originals: "原始材料", expanded: "展开文档", duplicate: "重复件", pending: "待发布", publish: "发布成功项", retry: "修复并重试", retryHint: "示例异常：模拟源文件已修复，重试后进入待发布。", failure: "示例损坏附件：内容提取失败，需修复后重试。", unsupported: "仅支持不超过 2 MB 的 UTF-8 .txt 文件。", empty: "未发现可读取的文本。", error: "文件读取失败。", batch: "导入批次", duplicateMark: "完全重复", parent: "直接父文档", already: "本项目已经导入此示例包；可使用真实文本继续体验。", indexed: "已发布文档可搜索；正文变化后索引状态同步更新。", fixedSource: "示例邮件包", textSource: "本地文本", reason: "异常原因", stagedHint: "待发布材料不会进入搜索或交付。", dedup: "仅标记重复，保留每次来源", inventoryHint: "示例中的原始材料与展开文档分别计数，附件不是额外上传文件。" },
  search: { label: "全文搜索", placeholder: '关键词或 "完整短语"；可用 AND / OR / NOT', run: "运行搜索", field: "筛选字段", operator: "匹配方式", value: "筛选值", add: "添加条件", remove: "移除", logic: "条件组合", and: "全部满足（AND）", or: "任一满足（OR）", fields: { source: "来源", type: "类型", name: "名称", reviewed: "审阅状态" }, operators: { contains: "包含", equals: "等于" }, save: "保存搜索", saved: "已保存搜索", searchName: "搜索名称", family: "包含父邮件及附件", direct: "直接命中", related: "关联带入", coverage: "索引覆盖", directCount: "直接命中", relatedCount: "关联带入", results: "当前结果", allFolders: "所有来源", folders: "来源文件夹", syntax: "检索式不完整：请检查运算符及双引号。本版不支持括号和邻近语法。", view: "默认文档视图", viewHint: "固定列表列；本版不开放 View 编辑器或统计看板。", bulk: "批量标注", bulkHint: "仅修改当前选中的文档；保留其他字段。", sort: "排序", sorts: { id: "编号升序", name: "名称升序", date: "日期降序" }, select: "选择文档", selectPage: "选择本页", export: "将所选加入交付", dateFrom: "开始日期", dateTo: "结束日期", nameRequired: "请输入搜索名称。", reviewed: "已审阅", unreviewed: "未审阅", noSelected: "请先选择至少一份文档。", countLabel: "份" },
  review: { zoomLevels: ["90%", "100%", "120%"], responsive: "相关性", confidential: "保密性", issues: "议题", notes: "备注", saveNext: "保存并下一份", previous: "沿用上一份标注", noPrevious: "没有可沿用的上一份记录。", previousApplied: "已填入允许复制的字段，请核对后保存。", family: "关联文档", history: "审阅修改历史", before: "修改前", after: "修改后", noDoc: "请先从文档列表打开一份文档。", back: "返回结果列表", find: "文档内查找", match: "处命中", zoom: "缩放", end: "已保存，当前范围已到最后一份。", dirty: "有未保存的修改。离开后将丢失，是否继续？", conflict: "另一窗口已修改数据。请刷新后重试，避免覆盖。", loading: "文档不可用或不属于当前项目。", downloadText: "下载当前文本", copyHint: "只复制表单配置中允许沿用的字段。" },
  analytics: { index: "默认全文索引", refresh: "更新索引", last: "最近更新时间", run: "运行示例分析", sample: "邮件链 / 近似分组为预设样本结果，不对上传文件运行真实分析算法。", thread: "邮件链", similar: "近似文档组", language: "语言分布", group: "分组", show: "查看组内文档", important: "重点邮件", noGroup: "未分组", other: "用户文本（未分析）", languages: { zh: "中文", en: "英文", unknown: "未分析" }, criteria: "范围：本项目已发布文档；字段：提取文本；维护由系统承担。" },
  export: { draft: "本次交付", choose: "选择交付范围", all: "全部已审阅文档", selected: "从列表选中的文档", freeze: "冻结本次文档集合", frozen: "已冻结", check: "交付前检查", build: "制作并下载", meta: "元数据 CSV", text: "提取文本 TXT", hint: "本版可生成真实 ZIP 示例交付包（文本、元数据及 manifest）。不输出原件、Bates、PDF、load file 或遮盖结果。", blocked: "交付被阻断：范围为空、含未审阅/保密文档或未发布文档。请调整范围。", changed: "冻结后文档内容或标注发生变化，请重新冻结并检查。", passed: "检查通过，可以制作。", format: "至少选择一种输出。", history: "交付历史", version: "交付版本", again: "重新制作", empty: "尚未冻结文档范围。", manifest: "manifest.json", filename: "FACT-MVP", formatNote: "prototype-text-package; no native files, images, redactions or load files", snapshotNote: "下载历史版本保留当时的文档和标注；重新制作需重新检查当前版本。" },
  settings: { project: "工作区名称", client: "客户", matter: "事项", newProject: "新建工作区", admin: "项目管理员", member: "成员姓名", email: "邮箱", role: "角色组", newMember: "添加成员", lastAdmin: "至少保留一名启用的管理员。", form: "审阅表单名称", addField: "新增字段", label: "字段名称", options: "选项（逗号分隔）", required: "必填", visible: "显示在审阅页", readOnly: "只读", copyable: "允许沿用", showInReview: "显示在审阅页", editableInReview: "审阅时可编辑", carryForward: "允许从上一份带入", preview: "预览表单", fieldPageHint: "管理员在此维护字段名称、字段类型和选项内容；这些定义可被审阅表单使用。", reviewPageHint: "管理员在此决定字段是否显示、是否可编辑，以及点击“沿用上一份”时是否带入。", fieldType: "字段类型", fieldTypeOptions: [{ id: "text", label: "短文本" }, { id: "longText", label: "长文本" }, { id: "single", label: "单选" }, { id: "multi", label: "多选" }, { id: "date", label: "日期" }, { id: "number", label: "数字" }, { id: "boolean", label: "是 / 否" }] as const, fieldOptions: "选项内容", noOptions: "此类型不需要选项", text: "文本字段", single: "单选", multi: "多选", action: "操作", coreFieldHint: "相关性和保密性仍参与交付检查；调整其必填、显示或选项后，交付检查可能无法通过。", rule: "处理方案", ruleValue: "基础文本处理", timezone: "时区", timezoneValue: "Asia/Shanghai", dedup: "去重方式", parents: "保留直接父子关系", ruleHint: "处理规则由内部维护，本版展示有效规则；不提供规则编辑器。", backup: "下载项目备份", restore: "导入项目备份", restoreConfirm: "恢复将替换当前浏览器的全部 MVP 数据，是否继续？", invalidBackup: "备份结构无效，未修改现有数据。", restored: "已恢复备份。", backupHint: "备份包含本浏览器的全部项目、标注、审阅配置与任务。真实服务端备份、认证和权限仍需开发。", audit: "关键操作记录", active: "启用状态", protect: "相关性、保密性字段是交付检查的依据；其他字段可按项目需要配置。", adminHint: "三种预设角色组，无逐对象权限矩阵、模板复制或自由布局。" },
  audit: { project: "项目资料保存", member: "成员更新", fields: "字段与表单更新", review: "审阅保存", bulk: "批量标注", search: "保存搜索", export: "制作交付", restore: "备份恢复" },
  seed: { project: "马克欺诈项目", client: "Close AI Ltd.", matter: "高管马克欺诈调查", project2: "供应商合同项目", client2: "示例采购公司", matter2: "年度采购审查", admin: "林然", email: "linran@example.test", reviewer: "周宁", reviewerEmail: "zhouning@example.test", form: "基础审阅表单", issues: ["资金流向", "合同异常", "信息披露"], date: "2026-09-20", threadA: "投资款往来", similarA: "投资安排附件", threadB: "供应商沟通", langZh: "zh", langEn: "en", docs: [
    { id: "DOC-0001", name: "关于投资款安排.eml", type: "Email", source: "邮箱 / 马克", family: "F-01", parent: "", thread: "投资款往来", similar: "", language: "zh", date: "2026-09-18", content: "发件人：马克\n收件人：林然\n主题：关于投资款安排\n\n请核对本季度的投资款和收款账户。附件中有合同草案。投资项目尚待董事会审批，请勿提前披露。\n\nMark: the investment agreement requires approval." },
    { id: "DOC-0002", name: "投资协议草案.txt", type: "Text", source: "邮箱 / 马克", family: "F-01", parent: "DOC-0001", thread: "", similar: "投资安排附件", language: "zh", date: "2026-09-18", content: "投资协议草案\n\n投资款共计一百万元，用于项目设备采购。收款账户应与合同主体一致。付款前需要财务和项目负责人批准。" },
    { id: "DOC-0003", name: "回复：投资款安排.eml", type: "Email", source: "邮箱 / 林然", family: "F-02", parent: "", thread: "投资款往来", similar: "", language: "zh", date: "2026-09-19", content: "发件人：林然\n主题：回复：投资款安排\n\n已核对投资款，发现账户名称与供应商不一致，需要补充说明。\n\n原邮件：请核对本季度的投资款和收款账户。" },
    { id: "DOC-0004", name: "投资协议修订.txt", type: "Text", source: "邮箱 / 林然", family: "F-02", parent: "DOC-0003", thread: "", similar: "投资安排附件", language: "zh", date: "2026-09-19", content: "投资协议修订稿\n\n投资款共计一百万元，用于项目设备采购。收款账户须经供应商书面确认。付款前需要财务和董事会批准。" },
    { id: "DOC-0005", name: "Supplier meeting.eml", type: "Email", source: "邮箱 / 采购", family: "F-03", parent: "", thread: "供应商沟通", similar: "", language: "en", date: "2026-09-20", content: "Subject: Supplier meeting\n\nPlease review the supplier contract and payment terms. The meeting will take place next Monday. No investment decision has been made." },
    { id: "DOC-0006", name: "会议纪要.txt", type: "Text", source: "邮箱 / 采购", family: "F-03", parent: "DOC-0005", thread: "", similar: "", language: "zh", date: "2026-09-20", content: "会议纪要\n\n采购部需重新确认供应商报价。此次讨论不涉及项目融资。" },
    { id: "DOC-0007", name: "投资协议备份.txt", type: "Text", source: "共享目录", family: "F-04", parent: "", thread: "", similar: "投资安排附件", language: "zh", date: "2026-09-20", content: "投资协议草案\n\n投资款共计一百万元，用于项目设备采购。收款账户应与合同主体一致。付款前需要财务和项目负责人批准。" },
    { id: "DOC-0008", name: "待修复附件.txt", type: "Text", source: "共享目录", family: "F-05", parent: "", thread: "", similar: "", language: "zh", date: "2026-09-20", content: "修复后的附件内容：补充合同需要项目负责人审批。" },
  ] },
} as const;

export const mvpScope = [
  {
    "id": "FACT-ADM-01",
    "name": "客户档案",
    "priority": "M1"
  },
  {
    "id": "FACT-ADM-02",
    "name": "项目事项",
    "priority": "M0"
  },
  {
    "id": "FACT-ADM-03",
    "name": "项目工作区",
    "priority": "M0"
  },
  {
    "id": "FACT-ADM-05",
    "name": "成员账户管理",
    "priority": "M0"
  },
  {
    "id": "FACT-ADM-06",
    "name": "项目角色组与成员",
    "priority": "M0"
  },
  {
    "id": "FACT-ADM-07",
    "name": "基础角色授权",
    "priority": "M0"
  },
  {
    "id": "FACT-ADM-09",
    "name": "角色视角预览",
    "priority": "M1"
  },
  {
    "id": "FACT-ADM-10",
    "name": "项目管理员指定",
    "priority": "M1"
  },
  {
    "id": "FACT-CFG-01",
    "name": "审阅字段定义",
    "priority": "M0"
  },
  {
    "id": "FACT-CFG-02",
    "name": "议题选项维护",
    "priority": "M0"
  },
  {
    "id": "FACT-CFG-06",
    "name": "审阅表单管理",
    "priority": "M1"
  },
  {
    "id": "FACT-CFG-08",
    "name": "字段显示与只读规则",
    "priority": "M0"
  },
  {
    "id": "FACT-CFG-11",
    "name": "表单预览",
    "priority": "M1"
  },
  {
    "id": "FACT-CFG-12",
    "name": "表单接入审阅面板",
    "priority": "M0"
  },
  {
    "id": "FACT-CFG-13",
    "name": "允许复制的字段配置",
    "priority": "M1"
  },
  {
    "id": "FACT-ING-01",
    "name": "原始文件导入",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-03",
    "name": "数据源与处理批次",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-04",
    "name": "处理规则设置",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-05",
    "name": "导入前盘点",
    "priority": "M1"
  },
  {
    "id": "FACT-ING-06",
    "name": "文件识别与内容提取",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-07",
    "name": "附件展开与父子关系",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-08",
    "name": "完全重复识别",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-09",
    "name": "处理结果发布",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-10",
    "name": "处理异常定位",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-11",
    "name": "修复后重试",
    "priority": "M0"
  },
  {
    "id": "FACT-ING-13",
    "name": "处理结果对账",
    "priority": "M0"
  },
  {
    "id": "FACT-DOC-01",
    "name": "文档总清单",
    "priority": "M0"
  },
  {
    "id": "FACT-DOC-02",
    "name": "文件夹浏览",
    "priority": "M1"
  },
  {
    "id": "FACT-DOC-03",
    "name": "关键词与字段查询",
    "priority": "M0"
  },
  {
    "id": "FACT-DOC-04",
    "name": "组合条件编辑",
    "priority": "M1"
  },
  {
    "id": "FACT-DOC-05",
    "name": "搜索方案保存",
    "priority": "M1"
  },
  {
    "id": "FACT-DOC-06",
    "name": "连同附件和父邮件查看",
    "priority": "M0"
  },
  {
    "id": "FACT-DOC-07",
    "name": "文档批量标注",
    "priority": "M1"
  },
  {
    "id": "FACT-DOC-08",
    "name": "索引覆盖提示",
    "priority": "M0"
  },
  {
    "id": "FACT-ANA-01",
    "name": "搜索索引构建与维护",
    "priority": "M0"
  },
  {
    "id": "FACT-ANA-02",
    "name": "分析任务组织",
    "priority": "M1"
  },
  {
    "id": "FACT-ANA-03",
    "name": "邮件链与重点邮件",
    "priority": "M1"
  },
  {
    "id": "FACT-ANA-04",
    "name": "近似文档分组",
    "priority": "M1"
  },
  {
    "id": "FACT-ANA-05",
    "name": "文档语言识别",
    "priority": "M1"
  },
  {
    "id": "FACT-REV-02",
    "name": "文档内容查看",
    "priority": "M0"
  },
  {
    "id": "FACT-REV-03",
    "name": "文档内定位与缩放",
    "priority": "M0"
  },
  {
    "id": "FACT-REV-04",
    "name": "审阅结果填写与保存",
    "priority": "M0"
  },
  {
    "id": "FACT-REV-05",
    "name": "填写校验",
    "priority": "M0"
  },
  {
    "id": "FACT-REV-06",
    "name": "保存并审下一份",
    "priority": "M0"
  },
  {
    "id": "FACT-REV-07",
    "name": "沿用上一份标注",
    "priority": "M1"
  },
  {
    "id": "FACT-REV-08",
    "name": "关联文档导航",
    "priority": "M0"
  },
  {
    "id": "FACT-REV-09",
    "name": "审阅修改记录",
    "priority": "M0"
  },
  {
    "id": "FACT-EXP-01",
    "name": "交付文档集合",
    "priority": "M0"
  },
  {
    "id": "FACT-EXP-03",
    "name": "输出文件及元数据",
    "priority": "M0"
  },
  {
    "id": "FACT-EXP-06",
    "name": "交付前检查与阻断",
    "priority": "M0"
  },
  {
    "id": "FACT-EXP-07",
    "name": "制作任务运行",
    "priority": "M0"
  },
  {
    "id": "FACT-EXP-08",
    "name": "清单和交付包下载",
    "priority": "M0"
  },
  {
    "id": "FACT-EXP-09",
    "name": "交付版本与重新制作",
    "priority": "M1"
  },
  {
    "id": "FACT-OPS-01",
    "name": "项目进度概览",
    "priority": "M1"
  },
  {
    "id": "FACT-OPS-02",
    "name": "统一任务列表",
    "priority": "M0"
  },
  {
    "id": "FACT-OPS-03",
    "name": "任务详情与运行记录",
    "priority": "M0"
  },
  {
    "id": "FACT-OPS-04",
    "name": "跨页面状态与真实存储",
    "priority": "M0"
  },
  {
    "id": "FACT-OPS-05",
    "name": "关键操作审计与恢复",
    "priority": "M0"
  }
] as const;
