import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ArrowRight, Bell, BookOpen, ChevronDown, FileSearch, HelpCircle, LayoutDashboard, Menu, Network, PackageCheck, Search, Settings, Upload, User, ListTodo } from "lucide-react";
import { mvpCopy as t, mvpScope } from "../constants/copy";
import { Button, Panel, Modal, Badge, Drawer, IconButton, Toast } from "../components/UI";
import { type Answers, type Doc, type FieldSpec, type FieldType, type Package, type Project, type Query, type Role, type Store, canDeliver, compileSearch, download, emptyQuery, isReviewed, loadStore, log, makeProject, now, packageBytes, queryDocs, requiredMissing, sampleDocs, stamp, storageKey, task, uid, validStore } from "../state/mvp";
import "../styles/mvp.css";

type Page = typeof t.pages[number]["id"];
type Mutate = (fn:(p:Project)=>void,adminOnly?:boolean)=>boolean;
type Context = { p:Project; update:Mutate; role:Role; notify:(s:string)=>void };
const icons = [LayoutDashboard,Upload,Search,BookOpen,Network,PackageCheck,ListTodo,Settings];
function Label({name,children}:{name:string;children:ReactNode}) {return <label className="mvp-field"><span>{name}</span>{children}</label>;}
function Empty(){return <p className="mvp-empty">{t.none}</p>;}
function Grid({headers,children}:{headers:readonly string[];children:ReactNode}){return <div className="mvp-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}

export function MvpApp(){
  const initial=useMemo(loadStore,[]);const [store,setStore]=useState(initial.store);const storeRef=useRef(store);storeRef.current=store;
  const [loadError,setLoadError]=useState(initial.error);const [projectId,setProjectId]=useState(store.projects[0].id);const [role,setRole]=useState<Role>("admin");
  const [page,setPage]=useState<Page>("home");const [toast,setToast]=useState<string|null>(initial.error?t.storageLoadError:null);const [scope,setScope]=useState(false);const [dirty,setDirty]=useState(false);
  const p=store.projects.find(p=>p.id===projectId)??store.projects[0];
  useEffect(()=>{const handler=(e:StorageEvent)=>{if(e.key!==storageKey)return;try{const next=JSON.parse(e.newValue??"null");if(validStore(next)){setStore(next);setToast(t.review.conflict);}else setLoadError(true);}catch{setLoadError(true);}};window.addEventListener("storage",handler);return()=>window.removeEventListener("storage",handler);},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),6500);return()=>clearTimeout(id);},[toast]);
  useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty]);
  function persist(next:Store,restoring=false){
    if(loadError&&!restoring){setToast(t.storageLoadError);return false;}
    try{const raw=localStorage.getItem(storageKey);const current=raw?JSON.parse(raw):null;
      if(!restoring&&current&&current.revision!==storeRef.current.revision){if(validStore(current))setStore(current);setToast(t.review.conflict);return false;}
      next.revision=uid();localStorage.setItem(storageKey,JSON.stringify(next));storeRef.current=next;setStore(next);if(restoring)setLoadError(false);return true;
    }catch{setToast(t.storageError);return false;}
  }
  const update:Mutate=(fn,adminOnly=false)=>{
    if(role==="reader"||(adminOnly&&role!=="admin")){setToast(t.readonly);return false;}
    const next=structuredClone(storeRef.current);const target=next.projects.find(v=>v.id===p.id);if(!target)return false;
    try{fn(target);return persist(next);}catch(e){setToast(e instanceof Error?e.message:t.error);return false;}
  };
  const canLeave=()=>!dirty||window.confirm(t.review.dirty);
  const navigate=(next:Page)=>{if(canLeave()){setDirty(false);setPage(next);window.scrollTo(0,0);}};
  function createProject(name:string,client:string,matter:string){
    if(role!=="admin")return;if(store.projects.some(p=>p.name===name)){setToast(t.duplicate);return;}
    const next=structuredClone(store);const project=makeProject(name,client,matter);log(project,t.audit.project,name);next.projects.push(project);
    if(persist(next)){setProjectId(project.id);setPage("home");setToast(t.saved);}
  }
  async function restore(file?:File){if(!file||role!=="admin")return;try{const next:unknown=JSON.parse(await file.text());if(!validStore(next)){setToast(t.settings.invalidBackup);return;}if(!window.confirm(t.settings.restoreConfirm))return;if(persist(next,true)){setProjectId(next.projects[0].id);setToast(t.settings.restored);}}catch{setToast(t.settings.invalidBackup);}}
  const header=t.pages.find(x=>x.id===page)!;
  return <div className="app-shell mvp-shell">
    <aside className="sidebar mvp-nav"><button type="button" className="brand-mark mvp-logo" aria-label={t.brand} onClick={()=>navigate("home")}>{t.brand.slice(0,1)}</button><nav className="sidebar__nav">{t.pages.map((item,i)=>{const Icon=icons[i];return <button type="button" key={item.id} aria-current={page===item.id?"page":undefined} className={page===item.id?"is-active":""} onClick={()=>navigate(item.id)}><Icon aria-hidden size={19}/><span>{item.name}</span></button>;})}</nav><button type="button" className="icon-button mvp-scope" aria-label={t.header.menu} title={t.header.menu} onClick={()=>setScope(true)}><Menu size={20}/></button></aside>
    <div className="app-shell__main mvp-main"><header className="topbar mvp-top"><label className="workspace-switcher"><span className="workspace-switcher__client">{p.client}</span><select aria-label={t.currentProject} value={p.id} onChange={e=>{if(canLeave()){setDirty(false);setProjectId(e.target.value);setPage("home");}}}>{store.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="topbar__tools"><button type="button" className="global-search" onClick={()=>navigate("documents")}><Search size={16} aria-hidden="true"/><span>{t.header.search}</span></button><button type="button" className="scope-button" onClick={()=>setScope(true)}><FileSearch size={17} aria-hidden="true"/><span>{t.header.scope}</span><Badge tone="info">{mvpScope.length}</Badge></button><IconButton label={t.header.notifications} onClick={()=>setToast(t.header.notifications)}><Bell size={19}/></IconButton><IconButton label={t.header.help} onClick={()=>setToast(t.prototype)}><HelpCircle size={19}/></IconButton><label className="mvp-role-picker"><span>{t.previewRole}</span><select aria-label={t.previewRole} value={role} onChange={e=>{if(canLeave()){setDirty(false);setRole(e.target.value as Role);setPage("home");}}}>{Object.entries(t.roles).map(([k,v])=><option key={k} value={v}>{v}</option>)}</select></label><button type="button" className="user-button" onClick={()=>navigate("settings")}><User size={18} aria-hidden="true"/><span>{t.header.user}</span><ChevronDown size={14} aria-hidden="true"/></button></div></header>
    <div className="mvp-banner">{t.prototype}{role!=="admin"&&<span>{t.roleHint}</span>}</div>{loadError&&<p role="alert" className="mvp-alert">{t.storageLoadError}</p>}
    <main className="page-canvas mvp-content"><header className="page-header mvp-heading"><div className="page-header__copy"><div className="page-header__eyebrow"><span className="feature-ids">{t.edition}</span><span className="mvp-eyebrow">{p.client}{t.dash}{p.matter}</span></div><h1>{header.name}</h1><p>{header.desc}</p></div></header>
    <Workspace key={p.id} {...{p,update,role,page,navigate,setDirty}} notify={setToast} onCreate={createProject} onRestore={restore} onBackup={()=>download("FACT-MVP-backup.json",localStorage.getItem(storageKey)??JSON.stringify(store,null,2),"application/json")}/>
    </main><footer className="prototype-footer"><span>{t.prototype}</span><span>{t.header.synthetic}</span><span>{t.header.version}</span><span>{t.header.demoOnly}</span></footer></div>
    <Drawer open={scope} title={t.scopeTitle} onClose={()=>setScope(false)}><p>{t.scopeHint}</p><Grid headers={[t.id,t.name,t.status]}>{mvpScope.map(f=><tr key={f.id}><td>{f.id}</td><td>{f.name}</td><td><Badge tone={f.priority==="M0"?"info":"neutral"}>{f.priority}</Badge></td></tr>)}</Grid></Drawer>
    <Toast message={toast} onClose={()=>setToast(null)}/>
  </div>;
}

function Workspace(props:Context&{page:Page;navigate:(p:Page)=>void;setDirty:(d:boolean)=>void;onCreate:(n:string,c:string,m:string)=>void;onBackup:()=>void;onRestore:(f?:File)=>void}){
  const {p,update,role,notify,page,navigate,setDirty}=props;
  const [query,setQuery]=useState(emptyQuery);const [selected,setSelected]=useState<string[]>([]);const [activeId,setActiveId]=useState("");const [reviewScope,setReviewScope]=useState<string[]>([]);const [previous,setPrevious]=useState<Answers|null>(null);const [exportIds,setExportIds]=useState<string[]>([]);const [analysisIds,setAnalysisIds]=useState<string[]|null>(null);
  const result=useMemo(()=>{try{const r=queryDocs(p.docs,query);return {...r,docs:analysisIds?r.docs.filter(d=>analysisIds.includes(d.id)):r.docs,error:""};}catch(e){return {docs:[],directIds:new Set<string>(),error:(e as Error).message};}},[p.docs,query,analysisIds]);
  const changeQuery=(q:Query)=>{setAnalysisIds(null);setQuery(q);};
  const openDoc=(id:string,scope?:string[])=>{setActiveId(id);if(scope)setReviewScope(scope);navigate("review");};
  if(page==="home")return <><div className="mvp-stats">{[[t.total,p.docs.filter(d=>d.state==="ready").length],[t.reviewed,p.docs.filter(isReviewed).length],[t.indexed,p.docs.filter(d=>d.state==="ready").length],[t.failures,p.docs.filter(d=>d.state==="failed").length]].map(([label,value])=><Panel key={label}><span>{label}</span><strong>{value}</strong></Panel>)}</div><Panel title={t.home.path}><div className="mvp-steps">{(["processing","documents","review","production"] as const).map((page,i)=><Button key={page} onClick={()=>navigate(page)}>{t.home.steps[i]}<ArrowRight size={16}/></Button>)}</div><p className="mvp-help">{t.home.hint}</p></Panel><TaskList p={p}/></>;
  if(page==="processing")return <Processing {...{p,update,role,notify}}/>;
  if(page==="documents")return <Documents {...{p,update,role,notify,query,selected,setSelected,result}} setQuery={changeQuery} openDoc={id=>openDoc(id,result.docs.map(d=>d.id))} toExport={()=>{if(!selected.length)return notify(t.search.noSelected);setExportIds(selected);navigate("production");}}/>;
  if(page==="review"){const doc=p.docs.find(d=>d.id===activeId&&d.state==="ready");return doc?<Review key={doc.id} {...{p,update,role,notify,doc,previous,setPrevious,setDirty}} next={()=>{const pos=reviewScope.indexOf(doc.id);const id=reviewScope.slice(pos+1).find(id=>p.docs.some(d=>d.id===id&&d.state==="ready"));if(id){setDirty(false);setActiveId(id);}else notify(t.review.end);}} openDoc={id=>{setDirty(false);setActiveId(id);}} back={()=>navigate("documents")}/>:<Panel><p>{t.review.noDoc}</p><Button onClick={()=>navigate("documents")}>{t.review.back}</Button></Panel>;}
  if(page==="analytics")return <Analytics {...{p,update,role,notify}} show={ids=>{setQuery({...emptyQuery(),family:false});setAnalysisIds(ids);setSelected([]);navigate("documents");}}/>;
  if(page==="production")return <Production {...{p,update,role,notify,exportIds}}/>;
  if(page==="tasks")return <><TaskList p={p}/><Panel title={t.settings.audit}><Grid headers={[t.time,t.action,t.actor,t.detail]}>{p.audit.map((a,i)=><tr key={i}><td>{stamp(a.at)}</td><td>{a.action}</td><td>{a.actor}</td><td>{a.detail}</td></tr>)}</Grid>{!p.audit.length&&<Empty/>}</Panel></>;
  return <SettingsPage {...props}/>;
}

function Processing({p,update,role,notify}:Context){
  const [inventory,setInventory]=useState(false);const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  const staged=p.docs.filter(d=>d.state==="staged");const failed=p.docs.filter(d=>d.state==="failed");
  async function files(list:FileList|null){if(!list?.length||role!=="admin")return;setBusy(true);const docs:Doc[]=[];const batch=uid();try{
    for(const file of Array.from(list)){if(!file.name.toLowerCase().endsWith(".txt")||file.size>2*1024*1024){notify(t.import.unsupported);return;}const content=await file.text();if(!content.trim()){notify(t.import.empty);return;}
      const id=uid();const duplicate=[...p.docs,...docs].find(d=>d.content===content)?.id??"";
      docs.push({id,name:file.name,type:"Text",source:t.import.textSource,family:id,parent:"",thread:"",similar:"",language:"unknown",date:new Date().toISOString().slice(0,10),content,state:"staged",batch,duplicate,version:1,values:{},history:[],fixture:false});}
    if(update(next=>{next.docs.push(...docs);task(next,"import",docs.length,batch);log(next,t.tasks.import,docs.map(d=>d.name).join("; "));},true))notify(t.saved);
  }catch{notify(t.import.error);}finally{setBusy(false);if(input.current)input.current.value="";}}
  return <><Panel title={t.import.inventory}><p>{t.import.hint}</p><div className="mvp-toolbar"><Button onClick={()=>setInventory(true)} disabled={role!=="admin"}>{t.import.fixture}</Button><Button onClick={()=>input.current?.click()} disabled={role!=="admin"||busy}>{t.import.local}</Button><input ref={input} type="file" accept=".txt,text/plain" multiple hidden onChange={e=>files(e.target.files)}/><Button variant="primary" disabled={!staged.length||role!=="admin"} onClick={()=>{if(update(next=>{next.docs.filter(d=>d.state==="staged").forEach(d=>{d.state="ready";d.version++;});next.indexedAt=now();task(next,"publish",staged.length,t.import.indexed);},true))notify(t.saved);}}>{t.import.publish}{t.dash}{staged.length}</Button></div><p className="mvp-help">{t.import.stagedHint}</p></Panel>
    <div className="mvp-stats">{[[t.import.expanded,p.docs.length],[t.import.pending,staged.length],[t.failures,failed.length],[t.import.duplicate,p.docs.filter(d=>d.duplicate).length]].map(([name,value])=><Panel key={name}><span>{name}</span><strong>{value}</strong></Panel>)}</div>
    <Panel title={t.import.batch}><Grid headers={[t.file,t.source,t.status,t.import.parent,t.import.duplicateMark,t.action]}>{p.docs.map(d=><tr key={d.id}><td><strong>{d.name}</strong><small>{d.batch}</small></td><td>{d.source}</td><td><Badge tone={d.state==="failed"?"danger":d.state==="ready"?"success":"warning"}>{t.states[d.state]}</Badge>{d.state==="failed"&&<small>{t.import.failure}</small>}</td><td>{d.parent||t.dash}</td><td>{d.duplicate||t.dash}</td><td>{d.state==="failed"&&<Button disabled={role!=="admin"} onClick={()=>{if(update(next=>{const doc=next.docs.find(v=>v.id===d.id)!;doc.state="staged";doc.version++;task(next,"retry",1,t.import.retryHint);},true))notify(t.import.retryHint);}}>{t.import.retry}</Button>}</td></tr>)}</Grid>{!p.docs.length&&<Empty/>}</Panel>
    <Modal open={inventory} title={t.import.preview} onClose={()=>setInventory(false)} footer={<><Button onClick={()=>setInventory(false)}>{t.cancel}</Button><Button variant="primary" onClick={()=>{if(p.docs.some(d=>d.fixture)){notify(t.import.already);return;}if(update(next=>{next.docs.push(...sampleDocs());task(next,"import",t.seed.docs.length,t.import.fixedSource,"error");log(next,t.tasks.import,t.import.fixedSource);},true)){setInventory(false);notify(t.saved);}}}>{t.import.submit}</Button></>}><div className="mvp-stats"><Panel><span>{t.import.originals}</span><strong>{t.seed.docs.filter(d=>!d.parent).length}</strong></Panel><Panel><span>{t.import.expanded}</span><strong>{t.seed.docs.length}</strong></Panel></div><p>{t.import.inventoryHint}</p><p>{t.import.failure}</p></Modal>
  </>;
}

type Result = ReturnType<typeof queryDocs>&{error:string};
function ReviewForm({fields,values,onChange,disabled=false}:{fields:FieldSpec[];values:Answers;onChange:(v:Answers)=>void;disabled?:boolean}){
  const setValue=(id:string,value:string)=>onChange({...values,[id]:value?[value]:[]});
  return <div className="mvp-form">{fields.filter(f=>f.visible).map(f=>{
    const value=values[f.id]?.[0]??"", locked=disabled||f.readOnly;
    const choices=[...new Set([...f.options,...(values[f.id]??[])])];
    let control:ReactNode;
    if(f.type==="single"||f.type==="boolean") control=<select value={value} disabled={locked} onChange={e=>setValue(f.id,e.target.value)}><option value="">{t.choose}</option>{choices.map(o=><option key={o}>{o}</option>)}</select>;
    else if(f.type==="multi") control=<span className="mvp-choices">{choices.map(o=><label key={o} className="mvp-check"><input type="checkbox" checked={values[f.id]?.includes(o)??false} disabled={locked} onChange={e=>onChange({...values,[f.id]:e.target.checked?[...(values[f.id]??[]),o]:(values[f.id]??[]).filter(v=>v!==o)})}/>{o}</label>)}</span>;
    else if(f.type==="date") control=<input type="date" value={value} disabled={locked} onChange={e=>setValue(f.id,e.target.value)}/>;
    else if(f.type==="number") control=<input type="number" value={value} disabled={locked} onChange={e=>setValue(f.id,e.target.value)}/>;
    else control=<textarea rows={f.type==="longText"?4:2} value={value} disabled={locked} onChange={e=>setValue(f.id,e.target.value)}/>;
    return <Label key={f.id} name={f.name+(f.required?` (${t.settings.required})`:"")}>{control}</Label>;
  })}</div>;
}
function Highlight({text,term}:{text:string;term:string}){if(!term)return <>{text}</>;const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return <>{text.split(new RegExp(`(${escaped})`,"gi")).map((s,i)=>s.toLowerCase()===term.toLowerCase()?<mark key={i}>{s}</mark>:s)}</>;}
function Review({p,update,role,notify,doc,previous,setPrevious,setDirty,next,openDoc,back}:Context&{doc:Doc;previous:Answers|null;setPrevious:(a:Answers)=>void;setDirty:(d:boolean)=>void;next:()=>void;openDoc:(id:string)=>void;back:()=>void}){
  const [values,setValues]=useState<Answers>(structuredClone(doc.values));const [version,setVersion]=useState(doc.version);const [find,setFind]=useState("");const [zoom,setZoom]=useState("normal");const [history,setHistory]=useState(false);
  const dirty=JSON.stringify(values)!==JSON.stringify(doc.values);useEffect(()=>{setDirty(dirty);return()=>setDirty(false);},[dirty,setDirty]);
  const change=(value:Answers)=>{setValues(value);setDirty(true);};
  function save(advance=false){if(requiredMissing(p.fields,values)){notify(t.required);return;}if(doc.version!==version){notify(t.review.conflict);return;}
    if(update(project=>{const d=project.docs.find(v=>v.id===doc.id)!;if(d.version!==version)throw new Error(t.review.conflict);const before=structuredClone(d.values);d.values=structuredClone(values);d.version++;d.history.push({at:now(),actor:t.seed.admin,before,after:structuredClone(values)});log(project,t.audit.review,d.id);})){setVersion(version+1);setPrevious(structuredClone(values));setDirty(false);notify(t.saved);if(advance)next();}}
  const family=p.docs.filter(d=>d.id!==doc.id&&d.family===doc.family&&d.state==="ready");
  return <><div className="mvp-toolbar"><Button onClick={back}>{t.review.back}</Button><Badge tone="info">{doc.id}</Badge><span>{doc.name}</span></div><div className="mvp-review-grid"><Panel title={doc.name} subtitle={`${doc.source}${t.dash}${doc.date}`}><div className="mvp-toolbar"><Label name={t.review.find}><input value={find} onChange={e=>setFind(e.target.value)}/></Label><Label name={t.review.zoom}><select value={zoom} onChange={e=>setZoom(e.target.value)}>{["small","normal","large"].map((v,i)=><option key={v} value={v}>{t.review.zoomLevels[i]}</option>)}</select></Label><span>{find?doc.content.toLowerCase().split(find.toLowerCase()).length-1:0}{t.review.match}</span></div><article className={`mvp-paper mvp-paper--${zoom}`}><Highlight text={doc.content} term={find}/></article><div className="mvp-toolbar"><Button onClick={()=>download(`${doc.id}.txt`,doc.content,"text/plain;charset=utf-8")}>{t.review.downloadText}</Button><Button onClick={()=>setHistory(true)}>{t.review.history}</Button></div><h3>{t.review.family}</h3><div className="mvp-toolbar">{family.map(d=><Button key={d.id} onClick={()=>{if(!dirty||window.confirm(t.review.dirty))openDoc(d.id);}}>{d.name}</Button>)}{!family.length&&<span>{t.none}</span>}</div></Panel>
    <Panel title={p.form}><ReviewForm fields={p.fields} values={values} onChange={change} disabled={role==="reader"}/><div className="mvp-form"><Button disabled={role==="reader"} onClick={()=>{if(!previous)return notify(t.review.noPrevious);const next=structuredClone(values);p.fields.filter(f=>f.copyable&&!f.readOnly&&f.visible).forEach(f=>{next[f.id]=previous[f.id]??[];});change(next);notify(t.review.previousApplied);}}>{t.review.previous}</Button><p className="mvp-help">{t.review.copyHint}</p><Button disabled={role==="reader"} onClick={()=>save()}>{t.save}</Button><Button variant="primary" disabled={role==="reader"} onClick={()=>save(true)}>{t.review.saveNext}</Button></div></Panel></div>
    <Modal open={history} title={t.review.history} onClose={()=>setHistory(false)} wide><Grid headers={[t.time,t.actor,t.review.before,t.review.after]}>{doc.history.map((h,i)=><tr key={i}><td>{stamp(h.at)}</td><td>{h.actor}</td><td>{Object.values(h.before).flat().join(t.dash)||t.dash}</td><td>{Object.values(h.after).flat().join(t.dash)||t.dash}</td></tr>)}</Grid>{!doc.history.length&&<Empty/>}</Modal></>;
}

function Analytics({p,update,role,notify,show}:Context&{show:(ids:string[])=>void}){
  const docs=p.docs.filter(d=>d.state==="ready");const [kind,setKind]=useState<"thread"|"similar"|"language">("thread");
  const grouped=docs.reduce<Record<string,Doc[]>>((r,d)=>{const key=d[kind]||t.analytics.noGroup;(r[key]??=[]).push(d);return r;},{});
  return <><Panel title={t.analytics.index} actions={<Button disabled={role!=="admin"} onClick={()=>{if(update(next=>{next.indexedAt=now();task(next,"index",docs.length,t.analytics.criteria);},true))notify(t.saved);}}>{t.analytics.refresh}</Button>}><div className="mvp-toolbar"><Badge tone="success">{t.indexed}{t.dash}{docs.length}</Badge><span>{t.analytics.last}{t.dash}{stamp(p.indexedAt)}</span></div><p>{t.analytics.criteria}</p></Panel><Panel title={t.tasks.analysis} actions={<Button disabled={role!=="admin"} onClick={()=>{if(update(next=>{next.analysisAt=now();task(next,"analysis",docs.length,t.analytics.sample);},true))notify(t.saved);}}>{t.analytics.run}</Button>}><p className="mvp-alert">{t.analytics.sample}</p><div className="mvp-toolbar">{(["thread","similar","language"] as const).map(k=><Button key={k} variant={kind===k?"primary":"secondary"} onClick={()=>setKind(k)}>{t.analytics[k]}</Button>)}</div>{p.analysisAt?<><p>{t.analytics.last}{t.dash}{stamp(p.analysisAt)}</p><Grid headers={[t.analytics.group,t.count,t.analytics.important,t.action]}>{Object.entries(grouped).map(([name,items])=><tr key={name}><td>{kind==="language"?t.analytics.languages[name as keyof typeof t.analytics.languages]??name:name}</td><td>{items.length}</td><td>{kind==="thread"&&name!==t.analytics.noGroup?[...items].sort((a,b)=>b.date.localeCompare(a.date))[0].name:t.dash}</td><td><Button onClick={()=>show(items.map(d=>d.id))}>{t.analytics.show}</Button></td></tr>)}</Grid></>:<Empty/>}</Panel></>;
}

function Production({p,update,role,notify,exportIds}:Context&{exportIds:string[]}){
  const [mode,setMode]=useState(exportIds.length?"selected":"all");const [frozen,setFrozen]=useState<Doc[]>([]);const [formats,setFormats]=useState({text:true,meta:true});const [passed,setPassed]=useState(false);
  const candidates=mode==="selected"?p.docs.filter(d=>exportIds.includes(d.id)):p.docs.filter(isReviewed);
  const unchanged=()=>frozen.every(d=>p.docs.find(v=>v.id===d.id)?.version===d.version);
  function check(){if(!unchanged()){notify(t.export.changed);setPassed(false);return false;}if(!canDeliver(frozen,p.fields)){notify(t.export.blocked);setPassed(false);return false;}if(!formats.text&&!formats.meta){notify(t.export.format);setPassed(false);return false;}setPassed(true);notify(t.export.passed);return true;}
  function build(){if(role==="reader")return;if(!check())return;const pkg:Package={id:uid(),at:now(),docs:structuredClone(frozen),...formats};const bytes=packageBytes(pkg);if(update(next=>{next.packages.unshift(pkg);task(next,"export",pkg.docs.length,pkg.id);log(next,t.audit.export,pkg.id);})){download(`${t.export.filename}-${pkg.id.slice(0,8)}.zip`,bytes,"application/zip");setPassed(false);}}
  return <><Panel title={t.export.draft}><p>{t.export.hint}</p><div className="mvp-toolbar"><Label name={t.export.choose}><select value={mode} onChange={e=>{setMode(e.target.value);setPassed(false);}}><option value="all">{t.export.all}</option><option value="selected">{t.export.selected}</option></select></Label><Button disabled={!candidates.length||role==="reader"} onClick={()=>{setFrozen(structuredClone(candidates));setPassed(false);}}>{t.export.freeze}{t.dash}{candidates.length}</Button></div><div className="mvp-toolbar">{(["text","meta"] as const).map(k=><label key={k} className="mvp-check"><input type="checkbox" checked={formats[k]} onChange={e=>{setFormats({...formats,[k]:e.target.checked});setPassed(false);}}/>{t.export[k]}</label>)}</div><Grid headers={[t.id,t.file,t.review.responsive,t.review.confidential]}>{frozen.map(d=><tr key={d.id}><td>{d.id}</td><td>{d.name}</td><td>{d.values.responsive?.join(t.dash)||t.answers.pending}</td><td>{d.values.confidential?.join(t.dash)||t.dash}</td></tr>)}</Grid>{!frozen.length&&<p className="mvp-empty">{t.export.empty}</p>}<div className="mvp-toolbar"><Button disabled={!frozen.length||role==="reader"} onClick={check}>{t.export.check}</Button><Button variant="primary" disabled={!passed||role==="reader"} onClick={build}>{t.export.build}</Button>{passed&&<Badge tone="success">{t.export.passed}</Badge>}</div></Panel><Panel title={t.export.history}><p className="mvp-help">{t.export.snapshotNote}</p><Grid headers={[t.export.version,t.time,t.count,t.action]}>{p.packages.map((pkg,i)=><tr key={pkg.id}><td>{p.packages.length-i}{t.dash}{pkg.id.slice(0,8)}</td><td>{stamp(pkg.at)}</td><td>{pkg.docs.length}</td><td><div className="mvp-toolbar"><Button disabled={role==="reader"} onClick={()=>download(`${t.export.filename}-${pkg.id.slice(0,8)}.zip`,packageBytes(pkg),"application/zip")}>{t.download}</Button><Button disabled={role==="reader"} onClick={()=>{setFrozen(structuredClone(p.docs.filter(d=>pkg.docs.some(v=>v.id===d.id))));setFormats({text:pkg.text,meta:pkg.meta});setPassed(false);}}>{t.export.again}</Button></div></td></tr>)}</Grid>{!p.packages.length&&<Empty/>}</Panel></>;
}

function TaskList({p}:{p:Project}){const [filter,setFilter]=useState("all");const [active,setActive]=useState<string|null>(null);const item=p.tasks.find(t=>t.id===active);return <Panel title={t.recent}><div className="mvp-toolbar"><Label name={t.status}><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t.all}</option><option value="done">{t.done}</option><option value="error">{t.error}</option></select></Label></div><Grid headers={[t.time,t.type,t.count,t.status,t.action]}>{p.tasks.filter(x=>filter==="all"||x.state===filter).map(x=><tr key={x.id}><td>{stamp(x.at)}</td><td>{t.tasks[x.kind]}</td><td>{x.count}</td><td><Badge tone={x.state==="done"?"success":"warning"}>{x.state==="done"?t.done:t.error}</Badge></td><td><Button onClick={()=>setActive(x.id)}>{t.detail}</Button></td></tr>)}</Grid>{!p.tasks.length&&<Empty/>}<Modal open={!!item} title={t.detail} onClose={()=>setActive(null)}>{item&&<><p>{item.id}</p><p>{t.tasks[item.kind]}{t.dash}{stamp(item.at)}</p><p>{item.detail}</p></>}</Modal></Panel>;}

function SettingsPage({p,update,role,notify,onCreate,onBackup,onRestore}:Context&{onCreate:(n:string,c:string,m:string)=>void;onBackup:()=>void;onRestore:(f?:File)=>void}){
  const [tab,setTab]=useState<string>(t.settingsTabs[0]);const [project,setProject]=useState({name:p.name,client:p.client,matter:p.matter});const [newOpen,setNewOpen]=useState(false);const [newP,setNewP]=useState({name:"",client:"",matter:""});
  const [members,setMembers]=useState(structuredClone(p.members));const [member,setMember]=useState({name:"",email:"",role:"reviewer" as Role});const [adminId,setAdminId]=useState(p.adminId);
  const [fields,setFields]=useState(structuredClone(p.fields));const [form,setForm]=useState(p.form);const [preview,setPreview]=useState(false);const [previewValues,setPreviewValues]=useState<Answers>({});const [fieldName,setFieldName]=useState("");const [fieldType,setFieldType]=useState<FieldType>("single");const [fieldOptions,setFieldOptions]=useState(t.seed.issues.join(", "));const input=useRef<HTMLInputElement>(null);const editable=role==="admin";
  const typeLabel=(type:FieldType)=>t.settings.fieldTypeOptions.find(option=>option.id===type)?.label??type;
  const needsOptions=(type:FieldType)=>["single","multi","boolean"].includes(type);
  const saveFields=()=>{const cleaned=fields.map(f=>({...f,options:f.options.map(v=>v.trim()).filter(Boolean)}));if(cleaned.some(f=>needsOptions(f.type)&&!f.options.length))return notify(t.required);if(update(next=>{next.fields=cleaned;log(next,t.audit.fields,cleaned.map(f=>f.name).join(", "));},true)){setFields(cleaned);notify(t.saved);}};
  const saveReview=()=>{if(!form.trim())return notify(t.required);if(update(next=>{next.form=form.trim();next.fields=fields;log(next,t.audit.fields,form.trim());},true))notify(t.saved);};
  const addField=()=>{const name=fieldName.trim();const options=fieldOptions.split(/[,，]/).map(v=>v.trim()).filter(Boolean);if(!name||fields.some(f=>f.name===name))return notify(t.duplicate);if(needsOptions(fieldType)&&!options.length)return notify(t.required);setFields([...fields,{id:uid(),name,type:fieldType,options,required:false,visible:true,readOnly:false,copyable:fieldType!=="text"&&fieldType!=="longText"}]);setFieldName("");};
  function saveMembers(){if(!members.some(m=>m.id===adminId&&m.role==="admin"&&m.active))return notify(t.settings.lastAdmin);if(update(next=>{next.members=members;next.adminId=adminId;log(next,t.audit.member,members.map(m=>m.name).join(", "));},true))notify(t.saved);}
  return <><div className="mvp-tabs">{t.settingsTabs.map(v=><Button key={v} variant={tab===v?"primary":"secondary"} onClick={()=>setTab(v)}>{v}</Button>)}</div>
    {tab===t.settingsTabs[0]&&<Panel title={t.settingsTabs[0]} actions={<Button disabled={!editable} onClick={()=>setNewOpen(true)}>{t.settings.newProject}</Button>}><div className="mvp-form mvp-form--narrow">{(["name","client","matter"] as const).map(k=><Label key={k} name={k==="name"?t.settings.project:t.settings[k]}><input disabled={!editable} value={project[k]} onChange={e=>setProject({...project,[k]:e.target.value})}/></Label>)}<Button disabled={!editable} variant="primary" onClick={()=>{if(Object.values(project).some(v=>!v.trim()))return notify(t.required);if(update(next=>{Object.assign(next,project);log(next,t.audit.project,project.name);},true))notify(t.saved);}}>{t.save}</Button></div></Panel>}
    {tab===t.settingsTabs[1]&&<Panel title={t.settingsTabs[1]}><p>{t.settings.adminHint}</p><Grid headers={[t.settings.member,t.settings.email,t.settings.role,t.settings.active]}>{members.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.email}</td><td><select aria-label={`${t.settings.role} ${m.name}`} disabled={!editable} value={m.role} onChange={e=>setMembers(members.map(x=>x.id===m.id?{...x,role:e.target.value as Role}:x))}>{Object.entries(t.roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td><input aria-label={`${t.settings.active} ${m.name}`} type="checkbox" disabled={!editable} checked={m.active} onChange={e=>setMembers(members.map(x=>x.id===m.id?{...x,active:e.target.checked}:x))}/></td></tr>)}</Grid><div className="mvp-toolbar"><Label name={t.settings.admin}><select disabled={!editable} value={adminId} onChange={e=>setAdminId(e.target.value)}>{members.filter(m=>m.role==="admin"&&m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Label><Button disabled={!editable} onClick={saveMembers}>{t.save}</Button></div><h3>{t.settings.newMember}</h3><div className="mvp-toolbar"><Label name={t.settings.member}><input disabled={!editable} value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/></Label><Label name={t.settings.email}><input disabled={!editable} type="email" value={member.email} onChange={e=>setMember({...member,email:e.target.value})}/></Label><Label name={t.settings.role}><select disabled={!editable} value={member.role} onChange={e=>setMember({...member,role:e.target.value as Role})}>{Object.entries(t.roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Label><Button disabled={!editable} onClick={()=>{if(!member.name.trim()||!/^\S+@\S+\.\S+$/.test(member.email))return notify(t.required);if(members.some(x=>x.email.toLowerCase()===member.email.toLowerCase()))return notify(t.duplicate);setMembers([...members,{...member,id:uid(),active:true}]);setMember({name:"",email:"",role:"reviewer"});}}>{t.settings.newMember}</Button></div></Panel>}
    {tab===t.settingsTabs[2]&&<Panel title={t.settingsTabs[2]}><p>{t.settings.fieldPageHint}</p><Grid headers={[t.settings.label,t.settings.fieldType,t.settings.fieldOptions]}>{fields.map(f=><tr key={f.id}><td><strong>{f.name}</strong><small>{f.id}</small></td><td><select disabled={!editable} aria-label={`${t.settings.fieldType} ${f.name}`} value={f.type} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,type:e.target.value as FieldType,options:needsOptions(e.target.value as FieldType)?x.options:[]}:x))}>{t.settings.fieldTypeOptions.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></td><td>{needsOptions(f.type)?<input disabled={!editable} aria-label={`${t.settings.fieldOptions} ${f.name}`} value={f.options.join(", ")} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,options:e.target.value.split(/[,，]/)}:x))}/>:<span>{t.settings.noOptions}</span>}</td></tr>)}</Grid><p className="mvp-help">{t.settings.coreFieldHint}</p><div className="mvp-toolbar"><Label name={t.settings.label}><input disabled={!editable} value={fieldName} onChange={e=>setFieldName(e.target.value)} /></Label><Label name={t.settings.fieldType}><select disabled={!editable} value={fieldType} onChange={e=>{const next=e.target.value as FieldType;setFieldType(next);if(next==="boolean")setFieldOptions(`${t.answers.no}, ${t.answers.yes}`);else if(!needsOptions(next))setFieldOptions("");}}>{t.settings.fieldTypeOptions.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></Label>{needsOptions(fieldType)&&<Label name={t.settings.fieldOptions}><input disabled={!editable} value={fieldOptions} onChange={e=>setFieldOptions(e.target.value)} /></Label>}<Button disabled={!editable} onClick={addField}>{t.settings.addField}</Button><Button disabled={!editable} variant="primary" onClick={saveFields}>{t.save}</Button></div></Panel>}
    {tab===t.settingsTabs[3]&&<Panel title={t.settingsTabs[3]}><p>{t.settings.reviewPageHint}</p><Label name={t.settings.form}><input disabled={!editable} value={form} onChange={e=>setForm(e.target.value)} /></Label><Grid headers={[t.settings.label,t.settings.fieldType,t.settings.required,t.settings.showInReview,t.settings.editableInReview,t.settings.carryForward]}>{fields.map(f=><tr key={f.id}><td>{f.name}</td><td>{typeLabel(f.type)}</td><td><input type="checkbox" aria-label={`${t.settings.required} ${f.name}`} checked={f.required} disabled={!editable} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,required:e.target.checked}:x))}/></td><td><input type="checkbox" aria-label={`${t.settings.showInReview} ${f.name}`} checked={f.visible} disabled={!editable} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,visible:e.target.checked}:x))}/></td><td><input type="checkbox" aria-label={`${t.settings.editableInReview} ${f.name}`} checked={!f.readOnly} disabled={!editable} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,readOnly:!e.target.checked}:x))}/></td><td><input type="checkbox" aria-label={`${t.settings.carryForward} ${f.name}`} checked={f.copyable} disabled={!editable} onChange={e=>setFields(fields.map(x=>x.id===f.id?{...x,copyable:e.target.checked}:x))}/></td></tr>)}</Grid><p className="mvp-help">{t.settings.coreFieldHint}</p><div className="mvp-toolbar"><Button onClick={()=>setPreview(true)}>{t.settings.preview}</Button><Button disabled={!editable} variant="primary" onClick={saveReview}>{t.save}</Button></div></Panel>}
    {tab===t.settingsTabs[4]&&<Panel title={t.settings.rule}><dl className="mvp-def"><dt>{t.settings.rule}</dt><dd>{t.settings.ruleValue}</dd><dt>{t.settings.timezone}</dt><dd>{t.settings.timezoneValue}</dd><dt>{t.settings.dedup}</dt><dd>{t.import.dedup}</dd><dt>{t.settings.parents}</dt><dd>{t.yes}</dd></dl><p>{t.settings.ruleHint}</p></Panel>}
    {tab===t.settingsTabs[5]&&<Panel title={t.settingsTabs[5]}><p>{t.settings.backupHint}</p><div className="mvp-toolbar"><Button disabled={!editable} onClick={onBackup}>{t.settings.backup}</Button><Button disabled={!editable} onClick={()=>input.current?.click()}>{t.settings.restore}</Button><input hidden ref={input} type="file" accept=".json" onChange={e=>{onRestore(e.target.files?.[0]);e.target.value="";}}/></div></Panel>}
    <Modal open={preview} title={form} onClose={()=>setPreview(false)}><ReviewForm fields={fields} values={previewValues} onChange={setPreviewValues}/></Modal>
    <Modal open={newOpen} title={t.settings.newProject} onClose={()=>setNewOpen(false)} footer={<Button variant="primary" onClick={()=>{if(Object.values(newP).some(v=>!v.trim()))return notify(t.required);onCreate(newP.name.trim(),newP.client.trim(),newP.matter.trim());setNewOpen(false);}}>{t.create}</Button>}>{(["name","client","matter"] as const).map(k=><Label key={k} name={k==="name"?t.settings.project:t.settings[k]}><input value={newP[k]} onChange={e=>setNewP({...newP,[k]:e.target.value})}/></Label>)}</Modal>
  </>;
}

function Documents({p,update,role,notify,query,setQuery,selected,setSelected,result,openDoc,toExport}:Context&{query:Query;setQuery:(q:Query)=>void;selected:string[];setSelected:(v:string[])=>void;result:Result;openDoc:(id:string)=>void;toExport:()=>void}){
  const [draft,setDraft]=useState(query);const [page,setPage]=useState(0);const [sort,setSort]=useState("id");const [saveOpen,setSaveOpen]=useState(false);const [searchName,setSearchName]=useState("");const [bulk,setBulk]=useState(false);const [bulkValue,setBulkValue]=useState<string>(t.answers.relevant);
  useEffect(()=>{setDraft(query);setPage(0);},[query]);
  const sorted=[...result.docs].sort((a,b)=>sort==="date"?b.date.localeCompare(a.date):sort==="name"?a.name.localeCompare(b.name):a.id.localeCompare(b.id));
  const maxPage=Math.max(0,Math.ceil(sorted.length/5)-1);const currentPage=Math.min(page,maxPage);const visible=sorted.slice(currentPage*5,currentPage*5+5);
  function apply(q:Query){try{compileSearch(q.text);setQuery(q);setSelected([]);setPage(0);}catch{notify(t.search.syntax);}}
  return <div className="mvp-search-grid"><aside><Panel title={t.search.folders}><button className="mvp-folder" onClick={()=>apply({...draft,folder:""})}>{t.search.allFolders}</button>{[...new Set(p.docs.filter(d=>d.state==="ready").map(d=>d.source))].map(source=><button key={source} className={`mvp-folder ${query.folder===source?"active":""}`} onClick={()=>apply({...draft,folder:source})}>{source}</button>)}</Panel><Panel title={t.search.saved}>{p.searches.map(s=><div className="mvp-saved" key={s.id}><button onClick={()=>apply(structuredClone(s.query))}>{s.name}</button><Button disabled={role==="reader"} onClick={()=>update(next=>{next.searches=next.searches.filter(v=>v.id!==s.id);})}>{t.search.remove}</Button></div>)}{!p.searches.length&&<Empty/>}</Panel></aside>
    <section><Panel><form onSubmit={e=>{e.preventDefault();apply(draft);}}><div className="mvp-toolbar"><Label name={t.search.label}><input value={draft.text} placeholder={t.search.placeholder} onChange={e=>setDraft({...draft,text:e.target.value})}/></Label><Button variant="primary" type="submit">{t.search.run}</Button><Button onClick={()=>apply(emptyQuery())}>{t.reset}</Button><Button disabled={role==="reader"} onClick={()=>setSaveOpen(true)}>{t.search.save}</Button></div><div className="mvp-toolbar"><Label name={t.search.dateFrom}><input type="date" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></Label><Label name={t.search.dateTo}><input type="date" value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></Label><Label name={t.search.logic}><select value={draft.logic} onChange={e=>setDraft({...draft,logic:e.target.value as Query["logic"]})}><option value="and">{t.search.and}</option><option value="or">{t.search.or}</option></select></Label><Button onClick={()=>setDraft({...draft,conditions:[...draft.conditions,{field:"name",op:"contains",value:""}]})}>{t.search.add}</Button></div>
      {draft.conditions.map((c,i)=><div className="mvp-toolbar" key={i}><select aria-label={t.search.field} value={c.field} onChange={e=>setDraft({...draft,conditions:draft.conditions.map((x,n)=>n===i?{...x,field:e.target.value as typeof c.field}:x)})}>{Object.entries(t.search.fields).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label={t.search.operator} value={c.op} onChange={e=>setDraft({...draft,conditions:draft.conditions.map((x,n)=>n===i?{...x,op:e.target.value as typeof c.op}:x)})}>{Object.entries(t.search.operators).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input aria-label={t.search.value} value={c.value} onChange={e=>setDraft({...draft,conditions:draft.conditions.map((x,n)=>n===i?{...x,value:e.target.value}:x)})}/><Button onClick={()=>setDraft({...draft,conditions:draft.conditions.filter((_,n)=>n!==i)})}>{t.search.remove}</Button></div>)}
      </form><label className="mvp-check"><input type="checkbox" checked={query.family} onChange={e=>apply({...query,family:e.target.checked})}/>{t.search.family}</label><p className="mvp-help">{t.search.coverage}{t.dash}{p.docs.filter(d=>d.state==="ready").length}{t.dash}{t.import.pending}{t.dash}{p.docs.filter(d=>d.state!=="ready").length}</p></Panel>
      <Panel title={t.search.view} subtitle={t.search.viewHint} actions={<Badge tone="info">{t.search.results}{t.dash}{result.docs.length}</Badge>}><div className="mvp-toolbar"><span>{t.search.directCount}{t.dash}{result.docs.filter(d=>result.directIds.has(d.id)).length}{t.dash}{t.search.relatedCount}{t.dash}{result.docs.filter(d=>!result.directIds.has(d.id)).length}</span><Label name={t.search.sort}><select value={sort} onChange={e=>setSort(e.target.value)}>{Object.entries(t.search.sorts).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Label><Button disabled={!selected.length||role==="reader"} onClick={()=>setBulk(true)}>{t.search.bulk}{t.dash}{selected.length}</Button><Button disabled={!selected.length||role==="reader"} onClick={toExport}>{t.search.export}</Button></div>
      <Grid headers={[t.search.select,t.id,t.file,t.source,t.review.responsive,t.review.confidential,t.results]}>{visible.map(d=><tr key={d.id}><td><input type="checkbox" aria-label={`${t.search.select} ${d.id}`} checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(id=>id!==d.id))}/></td><td><button className="mvp-link" onClick={()=>openDoc(d.id)}>{d.id.slice(0,16)}</button></td><td><button className="mvp-link" onClick={()=>openDoc(d.id)}>{d.name}</button><small>{d.date}{t.dash}{d.type}</small></td><td>{d.source}</td><td>{d.values.responsive?.join(t.dash)||t.answers.pending}</td><td>{d.values.confidential?.join(t.dash)||t.dash}</td><td><Badge tone={result.directIds.has(d.id)?"info":"neutral"}>{result.directIds.has(d.id)?t.search.direct:t.search.related}</Badge></td></tr>)}</Grid>{!visible.length&&<p className="mvp-empty">{result.error||t.empty}</p>}<div className="mvp-toolbar"><label className="mvp-check"><input type="checkbox" checked={!!visible.length&&visible.every(d=>selected.includes(d.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(d=>d.id)])]:selected.filter(id=>!visible.some(d=>d.id===id)))}/>{t.search.selectPage}</label><Button onClick={()=>setPage(currentPage-1)} disabled={!currentPage}>{t.prev}</Button><span>{currentPage+1}{t.dash}{maxPage+1}{t.page}</span><Button disabled={currentPage>=maxPage} onClick={()=>setPage(currentPage+1)}>{t.next}</Button></div></Panel>
    </section>
    <Modal open={saveOpen} title={t.search.save} onClose={()=>setSaveOpen(false)} footer={<Button variant="primary" onClick={()=>{if(!searchName.trim())return notify(t.search.nameRequired);if(p.searches.some(s=>s.name===searchName.trim()))return notify(t.duplicate);if(update(next=>{next.searches.push({id:uid(),name:searchName.trim(),query:structuredClone(query)});log(next,t.audit.search,searchName.trim());})){setSaveOpen(false);setSearchName("");notify(t.saved);}}}>{t.save}</Button>}><Label name={t.search.searchName}><input value={searchName} onChange={e=>setSearchName(e.target.value)}/></Label><p>{query.text||t.all}</p></Modal>
    <Modal open={bulk} title={t.search.bulk} onClose={()=>setBulk(false)} footer={<Button variant="primary" onClick={()=>{if(update(next=>{next.docs.filter(d=>selected.includes(d.id)).forEach(d=>{const before=structuredClone(d.values);d.values.responsive=[bulkValue];d.version++;d.history.push({at:now(),actor:t.seed.admin,before,after:structuredClone(d.values)});});log(next,t.audit.bulk,selected.join(", "));})){setBulk(false);notify(t.saved);}}}>{t.save}</Button>}><p>{t.search.bulkHint}{t.dash}{selected.length}</p><Label name={t.review.responsive}><select value={bulkValue} onChange={e=>setBulkValue(e.target.value)}><option>{t.answers.relevant}</option><option>{t.answers.irrelevant}</option></select></Label></Modal>
  </div>;
}
